import fs from 'fs';

// Helper to sanitize and build members
const members: any[] = [];

// ==========================================
// 1. II.7.001 - VĂN TẤN TRUNG
// Phái II-VTQX (Quế Xuân)
// ==========================================
members.push({
  id: 'mem-701',
  fullName: 'Văn Tấn Trung',
  courtesyName: 'II.7.001',
  gender: 'male',
  generation: 7,
  branchId: 'branch-vtqx',
  phaiName: 'Phái II-VTQX',
  chiName: 'Quế Xuân',
  orderInFamily: 1,
  orderTitle: 'Trưởng Tộc Đời 7 (Phái II-VTQX)',
  isAlive: false,
  deathDateLunar: '11/04 ÂL',
  burialLocation: 'Trung Lôi, xã Phú Trạch (cải táng về Núi Đất, Quế Sơn, Quảng Nam)',
  bio: 'Con ông Văn Tấn Ba, cháu nội ông Văn Tấn Vinh. Mất ngày 11-4 ÂL. Mộ táng tại Trung Lôi, xã Phú Trạch, nay đã cải táng về Núi Đất, huyện Quế Sơn, tỉnh Quảng Nam.',
  fatherId: 'mem-601',
  motherId: 'mem-601-w',
  spouseIds: ['mem-701-w1', 'mem-701-w2', 'mem-701-w3'],
});

// Vợ chánh: Nguyễn Thị Hoãn
members.push({
  id: 'mem-701-w1',
  fullName: 'Nguyễn Thị Hoãn',
  gender: 'female',
  generation: 7,
  branchId: 'branch-vtqx',
  phaiName: 'Phái II-VTQX',
  chiName: 'Quế Xuân',
  orderInFamily: 1,
  orderTitle: 'Chánh Thất',
  isAlive: false,
  deathDateLunar: '13/11 ÂL',
  bio: 'Vợ chánh cụ Văn Tấn Trung. Mất ngày 13-11 ÂL. Sanh hạ 10 người con.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-701'],
});

// Vợ kế: Đặng Thị Trước
members.push({
  id: 'mem-701-w2',
  fullName: 'Đặng Thị Trước',
  gender: 'female',
  generation: 7,
  branchId: 'branch-vtqx',
  phaiName: 'Phái II-VTQX',
  chiName: 'Quế Xuân',
  orderInFamily: 2,
  orderTitle: 'Kế Thất',
  isAlive: false,
  burialLocation: 'Xứ Nước Ngọt, Qui Nhơn',
  bio: 'Vợ kế cụ Văn Tấn Trung. Mộ táng tại xứ Nước Ngọt, Qui Nhơn. Sanh hạ: Văn Tấn Tuệ, Văn Tấn Tài.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-701'],
});

// Vợ thứ: Đặng Thị Cách
members.push({
  id: 'mem-701-w3',
  fullName: 'Đặng Thị Cách',
  gender: 'female',
  generation: 7,
  branchId: 'branch-vtqx',
  phaiName: 'Phái II-VTQX',
  chiName: 'Quế Xuân',
  orderInFamily: 3,
  orderTitle: 'Thứ Thất',
  isAlive: false,
  burialLocation: 'Qui Nhơn',
  bio: 'Vợ thứ cụ Văn Tấn Trung. Mộ táng tại Qui Nhơn. Sanh hạ: Văn Tấn Điệt (Chiêm, Diệt).',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-701'],
});

// Các con của Văn Tấn Trung với Vợ chánh (Đời 8):
members.push(
  {
    id: 'mem-801-01',
    fullName: 'Văn vô danh',
    gender: 'male',
    generation: 8,
    branchId: 'branch-vtqx',
    phaiName: 'Phái II-VTQX',
    orderInFamily: 1,
    isAlive: false,
    bio: 'Con thứ 1 của cụ Văn Tấn Trung và bà Nguyễn Thị Hoãn.',
    fatherId: 'mem-701',
    motherId: 'mem-701-w1',
    spouseIds: [],
  },
  {
    id: 'mem-801-02',
    fullName: 'Văn Tấn Quận',
    gender: 'male',
    generation: 8,
    branchId: 'branch-vtqx',
    phaiName: 'Phái II-VTQX',
    orderInFamily: 2,
    isAlive: false,
    burialLocation: 'Xuân Phú',
    bio: 'Con thứ 2 của cụ Văn Tấn Trung và bà Nguyễn Thị Hoãn. Mộ táng tại Xuân Phú.',
    fatherId: 'mem-701',
    motherId: 'mem-701-w1',
    spouseIds: [],
  },
  {
    id: 'mem-801-03',
    fullName: 'Văn Tấn Trâu',
    gender: 'male',
    generation: 8,
    branchId: 'branch-vtqx',
    phaiName: 'Phái II-VTQX',
    orderInFamily: 3,
    isAlive: false,
    burialLocation: 'Mỹ Xuyên, xã T. giáp',
    bio: 'Con thứ 3 của cụ Văn Tấn Trung và bà Nguyễn Thị Hoãn. Mộ táng tại Mỹ Xuyên, xã T. giáp.',
    fatherId: 'mem-701',
    motherId: 'mem-701-w1',
    spouseIds: [],
  },
  {
    id: 'mem-801-04',
    fullName: 'Văn Thị Tường',
    gender: 'female',
    generation: 8,
    branchId: 'branch-vtqx',
    phaiName: 'Phái II-VTQX',
    orderInFamily: 4,
    isAlive: false,
    bio: 'Con gái thứ 4 của cụ Văn Tấn Trung và bà Nguyễn Thị Hoãn.',
    fatherId: 'mem-701',
    motherId: 'mem-701-w1',
    spouseIds: [],
  },
  {
    id: 'mem-801-05',
    fullName: 'Văn Thị Huyên',
    gender: 'female',
    generation: 8,
    branchId: 'branch-vtqx',
    phaiName: 'Phái II-VTQX',
    orderInFamily: 5,
    isAlive: false,
    bio: 'Con gái thứ 5 của cụ Văn Tấn Trung và bà Nguyễn Thị Hoãn.',
    fatherId: 'mem-701',
    motherId: 'mem-701-w1',
    spouseIds: [],
  },
  {
    // II.8.001: Văn Tấn Hiến (Biên)
    id: 'mem-801',
    fullName: 'Văn Tấn Hiến',
    courtesyName: 'Biên (II.8.001)',
    gender: 'male',
    generation: 8,
    branchId: 'branch-vtqx',
    phaiName: 'Phái II-VTQX',
    chiName: 'Quế Xuân',
    orderInFamily: 6,
    orderTitle: 'Trưởng Chi Đời 8 (II.8.001)',
    isAlive: false,
    deathDateLunar: '25/07 ÂL',
    burialLocation: 'xã Phú Trạch (cải táng về Núi Đất, Quế Sơn, Quảng Nam)',
    bio: 'Còn gọi là Biên. Con ông Văn Tấn Trung và bà Nguyễn Thị Hoãn, cháu nội ông Văn Tấn Ba. Mất ngày: 25-7 ÂL. Mộ táng tại xã Phú Trạch, nay đã cải táng về Núi Đất, huyện Quế Sơn, tỉnh Quảng Nam.',
    fatherId: 'mem-701',
    motherId: 'mem-701-w1',
    spouseIds: ['mem-801-w'],
  },
  {
    id: 'mem-801-07',
    fullName: 'Văn Thị Tai',
    courtesyName: 'Tư',
    gender: 'female',
    generation: 8,
    branchId: 'branch-vtqx',
    phaiName: 'Phái II-VTQX',
    orderInFamily: 7,
    isAlive: false,
    bio: 'Con gái thứ 7 của cụ Văn Tấn Trung và bà Nguyễn Thị Hoãn.',
    fatherId: 'mem-701',
    motherId: 'mem-701-w1',
    spouseIds: [],
  },
  {
    id: 'mem-801-08',
    fullName: 'Văn Thị Thái',
    gender: 'female',
    generation: 8,
    branchId: 'branch-vtqx',
    phaiName: 'Phái II-VTQX',
    orderInFamily: 8,
    isAlive: false,
    bio: 'Con gái thứ 8 của cụ Văn Tấn Trung và bà Nguyễn Thị Hoãn.',
    fatherId: 'mem-701',
    motherId: 'mem-701-w1',
    spouseIds: [],
  },
  {
    id: 'mem-801-09',
    fullName: 'Văn Tấn Ân',
    gender: 'male',
    generation: 8,
    branchId: 'branch-vtqx',
    phaiName: 'Phái II-VTQX',
    orderInFamily: 9,
    isAlive: false,
    bio: 'Con trai thứ 9 của cụ Văn Tấn Trung và bà Nguyễn Thị Hoãn.',
    fatherId: 'mem-701',
    motherId: 'mem-701-w1',
    spouseIds: [],
  },
  {
    id: 'mem-801-10',
    fullName: 'Văn Tấn Trân',
    gender: 'male',
    generation: 8,
    branchId: 'branch-vtqx',
    phaiName: 'Phái II-VTQX',
    orderInFamily: 10,
    isAlive: false,
    burialLocation: 'Qui Nhơn',
    bio: 'Con trai thứ 10 của cụ Văn Tấn Trung và bà Nguyễn Thị Hoãn. Mộ táng tại Qui Nhơn.',
    fatherId: 'mem-701',
    motherId: 'mem-701-w1',
    spouseIds: [],
  }
);

// Vợ của Văn Tấn Hiến (II.8.001):
members.push({
  id: 'mem-801-w',
  fullName: 'Đặng Thị Đặc',
  gender: 'female',
  generation: 8,
  branchId: 'branch-vtqx',
  phaiName: 'Phái II-VTQX',
  orderInFamily: 1,
  orderTitle: 'Phu Nhân',
  isAlive: false,
  bio: 'Vợ cụ Văn Tấn Hiến.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-801'],
});

// Các con đời 9 của Văn Tấn Hiến (II.8.001):
members.push(
  {
    id: 'mem-901-01',
    fullName: 'Văn vô danh',
    gender: 'male',
    generation: 9,
    branchId: 'branch-vtqx',
    phaiName: 'Phái II-VTQX',
    orderInFamily: 1,
    isAlive: false,
    bio: 'Con cụ Văn Tấn Hiến và bà Đặng Thị Đặc.',
    fatherId: 'mem-801',
    motherId: 'mem-801-w',
    spouseIds: [],
  },
  {
    id: 'mem-901-02',
    fullName: 'Văn Tấn Anh',
    gender: 'male',
    generation: 9,
    branchId: 'branch-vtqx',
    phaiName: 'Phái II-VTQX',
    orderInFamily: 2,
    isAlive: false,
    deathDateLunar: '16/09 ÂL',
    burialLocation: 'thôn An Đông, huyện Quế Sơn, tỉnh Quảng Nam',
    bio: 'Con cụ Văn Tấn Hiến và bà Đặng Thị Đặc. Mất ngày 16-9 ÂL, mộ táng tại thôn An Đông, huyện Quế Sơn.',
    fatherId: 'mem-801',
    motherId: 'mem-801-w',
    spouseIds: [],
  },
  {
    id: 'mem-901-03',
    fullName: 'Văn Tấn Khao',
    gender: 'male',
    generation: 9,
    branchId: 'branch-vtqx',
    phaiName: 'Phái II-VTQX',
    orderInFamily: 3,
    isAlive: false,
    deathDateLunar: '15/08 ÂL',
    burialLocation: 'xã Xuân Phú, huyện Quế Sơn, tỉnh Quảng Nam',
    bio: 'Con cụ Văn Tấn Hiến và bà Đặng Thị Đặc. Mất ngày 15-8 ÂL, mộ táng tại xã Xuân Phú, huyện Quế Sơn.',
    fatherId: 'mem-801',
    motherId: 'mem-801-w',
    spouseIds: [],
  },
  {
    id: 'mem-901-04',
    fullName: 'Văn Tấn Tình',
    gender: 'male',
    generation: 9,
    branchId: 'branch-vtqx',
    phaiName: 'Phái II-VTQX',
    orderInFamily: 4,
    isAlive: false,
    deathDateLunar: '17/01 ÂL',
    burialLocation: 'thôn An Đông, huyện Quế Sơn, tỉnh Quảng Nam',
    bio: 'Con cụ Văn Tấn Hiến và bà Đặng Thị Đặc. Mất ngày 17-1 ÂL, mộ táng tại thôn An Đông, Quế Sơn.',
    fatherId: 'mem-801',
    motherId: 'mem-801-w',
    spouseIds: [],
  },
  {
    id: 'mem-901-05',
    fullName: 'Văn Tấn Trí',
    gender: 'male',
    generation: 9,
    branchId: 'branch-vtqx',
    phaiName: 'Phái II-VTQX',
    orderInFamily: 5,
    isAlive: false,
    deathDateLunar: '16/04 ÂL',
    bio: 'Con cụ Văn Tấn Hiến và bà Đặng Thị Đặc. Mất ngày 16-4 ÂL.',
    fatherId: 'mem-801',
    motherId: 'mem-801-w',
    spouseIds: [],
  },
  {
    id: 'mem-901-06',
    fullName: 'Văn Tấn Hân',
    gender: 'male',
    generation: 9,
    branchId: 'branch-vtqx',
    phaiName: 'Phái II-VTQX',
    orderInFamily: 6,
    isAlive: false,
    burialLocation: 'xã Xuân Phú, huyện Quế Sơn, tỉnh Quảng Nam',
    bio: 'Con cụ Văn Tấn Hiến và bà Đặng Thị Đặc. Mộ táng tại xã Xuân Phú, Quế Sơn.',
    fatherId: 'mem-801',
    motherId: 'mem-801-w',
    spouseIds: [],
  }
);

// Con cụ Văn Tấn Trung với Vợ kế Đặng Thị Trước:
// II.8.002: Văn Tấn Tuệ (Huệ)
members.push({
  id: 'mem-802',
  fullName: 'Văn Tấn Tuệ',
  courtesyName: 'Huệ (II.8.002)',
  gender: 'male',
  generation: 8,
  branchId: 'branch-vtqx',
  phaiName: 'Phái II-VTQX',
  chiName: 'Quế Xuân',
  orderInFamily: 11,
  orderTitle: 'Thứ Chi Đời 8 (II.8.002)',
  isAlive: false,
  deathDateLunar: '30/12 ÂL',
  burialLocation: 'Xuân Mỹ, Bàn Lôi (cải táng về Núi Đất, Quế Sơn, Quảng Nam)',
  bio: 'Còn gọi là Văn Tấn Huệ. Con ông Văn Tấn Trung và bà Đặng Thị Trước. Mất ngày: 30-12 ÂL. Mộ táng tại Xuân Mỹ, Bàn Lôi, nay đã cải táng về Núi Đất, huyện Quế Sơn.',
  fatherId: 'mem-701',
  motherId: 'mem-701-w2',
  spouseIds: ['mem-802-w'],
});

members.push({
  id: 'mem-802-w',
  fullName: 'Phạm Thị Lữ',
  gender: 'female',
  generation: 8,
  branchId: 'branch-vtqx',
  phaiName: 'Phái II-VTQX',
  orderInFamily: 1,
  orderTitle: 'Phu Nhân (xã Kim Bồng)',
  isAlive: false,
  deathDateLunar: '21/01 ÂL',
  birthPlace: 'xã Kim Bồng',
  bio: 'Người xã Kim Bồng. Phu nhân cụ Văn Tấn Tuệ. Mất ngày 21-1 ÂL.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-802'],
});

// Con thứ 12 của Văn Tấn Trung: Văn Tấn Tài (Từ)
members.push({
  id: 'mem-801-12',
  fullName: 'Văn Tấn Tài',
  courtesyName: 'Từ',
  gender: 'male',
  generation: 8,
  branchId: 'branch-vtqx',
  phaiName: 'Phái II-VTQX',
  orderInFamily: 12,
  isAlive: false,
  bio: 'Con trai thứ 12 của cụ Văn Tấn Trung và bà Đặng Thị Trước.',
  fatherId: 'mem-701',
  motherId: 'mem-701-w2',
  spouseIds: [],
});

// Các con đời 9 của Văn Tấn Tuệ (II.8.002):
members.push(
  {
    id: 'mem-902-01',
    fullName: 'Văn Thị Duy',
    courtesyName: 'Quy',
    gender: 'female',
    generation: 9,
    branchId: 'branch-vtqx',
    phaiName: 'Phái II-VTQX',
    orderInFamily: 1,
    isAlive: false,
    bio: 'Con gái cụ Văn Tấn Tuệ và bà Phạm Thị Lữ.',
    fatherId: 'mem-802',
    motherId: 'mem-802-w',
    spouseIds: [],
  },
  {
    id: 'mem-902-02',
    fullName: 'Văn Thị Diêu',
    courtesyName: 'Văn Tấn Diệu',
    gender: 'female',
    generation: 9,
    branchId: 'branch-vtqx',
    phaiName: 'Phái II-VTQX',
    orderInFamily: 2,
    isAlive: false,
    deathDateLunar: '28/09 ÂL',
    burialLocation: 'xứ Mỹ, xã Dưỡng Mông, huyện Quế Sơn, Quảng Nam',
    bio: 'Mất ngày 28-9 ÂL. Mộ táng tại xứ Mỹ, xã Dưỡng Mông, huyện Quế Sơn.',
    fatherId: 'mem-802',
    motherId: 'mem-802-w',
    spouseIds: [],
  },
  {
    id: 'mem-902-03',
    fullName: 'Văn Tấn Tuấn',
    courtesyName: 'Tuân',
    gender: 'male',
    generation: 9,
    branchId: 'branch-vtqx',
    phaiName: 'Phái II-VTQX',
    orderInFamily: 3,
    isAlive: false,
    bio: 'Con cụ Văn Tấn Tuệ và bà Phạm Thị Lữ.',
    fatherId: 'mem-802',
    motherId: 'mem-802-w',
    spouseIds: [],
  },
  {
    id: 'mem-902-04',
    fullName: 'Văn Thị Bốn',
    courtesyName: 'Bà Bốn',
    gender: 'female',
    generation: 9,
    branchId: 'branch-vtqx',
    phaiName: 'Phái II-VTQX',
    orderInFamily: 4,
    isAlive: false,
    bio: 'Con gái cụ Văn Tấn Tuệ và bà Phạm Thị Lữ.',
    fatherId: 'mem-802',
    motherId: 'mem-802-w',
    spouseIds: [],
  },
  {
    id: 'mem-902-05',
    fullName: 'Văn Tấn Hoa',
    gender: 'male',
    generation: 9,
    branchId: 'branch-vtqx',
    phaiName: 'Phái II-VTQX',
    orderInFamily: 5,
    isAlive: false,
    bio: 'Con trai cụ Văn Tấn Tuệ và bà Phạm Thị Lữ.',
    fatherId: 'mem-802',
    motherId: 'mem-802-w',
    spouseIds: [],
  },
  {
    id: 'mem-902-06',
    fullName: 'Văn Thị Sáu',
    courtesyName: 'Bà Sáu',
    gender: 'female',
    generation: 9,
    branchId: 'branch-vtqx',
    phaiName: 'Phái II-VTQX',
    orderInFamily: 6,
    isAlive: false,
    bio: 'Con gái cụ Văn Tấn Tuệ và bà Phạm Thị Lữ.',
    fatherId: 'mem-802',
    motherId: 'mem-802-w',
    spouseIds: [],
  },
  {
    id: 'mem-902-07',
    fullName: 'Văn Thị Suy',
    courtesyName: 'Súy, Súng',
    gender: 'female',
    generation: 9,
    branchId: 'branch-vtqx',
    phaiName: 'Phái II-VTQX',
    orderInFamily: 7,
    isAlive: false,
    burialLocation: 'làng Dưỡng Mông',
    bio: 'Mộ táng ở làng Dưỡng Mông.',
    fatherId: 'mem-802',
    motherId: 'mem-802-w',
    spouseIds: [],
  },
  {
    id: 'mem-902-08',
    fullName: 'Văn Thị Ý',
    gender: 'female',
    generation: 9,
    branchId: 'branch-vtqx',
    phaiName: 'Phái II-VTQX',
    orderInFamily: 8,
    isAlive: false,
    burialLocation: 'làng Dưỡng Mông',
    bio: 'Mộ táng ở làng Dưỡng Mông.',
    fatherId: 'mem-802',
    motherId: 'mem-802-w',
    spouseIds: [],
  },
  {
    id: 'mem-902-09',
    fullName: 'Văn Thị Giã',
    courtesyName: 'Dã',
    gender: 'female',
    generation: 9,
    branchId: 'branch-vtqx',
    phaiName: 'Phái II-VTQX',
    orderInFamily: 9,
    isAlive: false,
    burialLocation: 'làng Dưỡng Mông',
    bio: 'Có chồng người họ Phạm, làng Phước Châu; con là Phạm Tư, Phạm Nhởn & Phạm Điển. Mộ táng ở làng Dưỡng Mông.',
    fatherId: 'mem-802',
    motherId: 'mem-802-w',
    spouseIds: [],
  }
);

// Con cụ Văn Tấn Trung với Vợ thứ Đặng Thị Cách:
// II.8.003: Văn Tấn Điệt (Chiêm, Diệt, Chí)
members.push({
  id: 'mem-803',
  fullName: 'Văn Tấn Điệt',
  courtesyName: 'Chiêm, Diệt, Chí (II.8.003)',
  gender: 'male',
  generation: 8,
  branchId: 'branch-vtqx',
  phaiName: 'Phái II-VTQX',
  chiName: 'Quế Xuân',
  orderInFamily: 13,
  orderTitle: 'Thứ Chi Đời 8 (II.8.003)',
  isAlive: false,
  bio: 'Thường gọi là: Chiêm, Diệt, Chí. Con ông Văn Tấn Trung và bà Đặng Thị Cách, cháu nội ông Văn Tấn Ba. Sanh hạ ông Văn Tấn Điện (biệt hữu gia phổ).',
  fatherId: 'mem-701',
  motherId: 'mem-701-w3',
  spouseIds: [],
});

members.push({
  id: 'mem-903-01',
  fullName: 'Văn Tấn Điện',
  courtesyName: 'Ông Điện',
  gender: 'male',
  generation: 9,
  branchId: 'branch-vtqx',
  phaiName: 'Phái II-VTQX',
  orderInFamily: 1,
  isAlive: false,
  bio: 'Con cụ Văn Tấn Điệt. Có hai người con là Ba Sơn và Sáu Núi. Theo Gia phả Tộc Văn Tấn ghi: Biệt hữu gia phổ.',
  fatherId: 'mem-803',
  motherId: null,
  spouseIds: [],
});

// ==========================================
// 2. II.7.002 - VĂN BÁ HẠNH (Văn Công Hạnh)
// Phái II-VBĐL (Đại Lộc) - Chi Hà Nha
// ==========================================
members.push({
  id: 'mem-702',
  fullName: 'Văn Bá Hạnh',
  courtesyName: 'Văn Công Hạnh (II.7.002)',
  gender: 'male',
  generation: 7,
  branchId: 'branch-vbdl',
  phaiName: 'Phái II-VBĐL',
  chiName: 'Chi HÀ NHA',
  orderInFamily: 1,
  orderTitle: 'Trưởng Nam Đời 7 (Chi Hà Nha)',
  isAlive: false,
  birthPlace: 'Hà Nha, Đại Đồng, huyện Đại Lộc, Quảng Nam',
  bio: 'Còn gọi là Văn Công Hạnh. Con ông Văn Bá Thể, cháu nội ông Văn Bá Hình. Kế tục chi Hà Nha.',
  fatherId: 'mem-602',
  motherId: 'mem-602-w',
  spouseIds: ['mem-702-w'],
});

members.push({
  id: 'mem-702-w',
  fullName: 'Huỳnh Thị Thao',
  courtesyName: 'Thiết',
  gender: 'female',
  generation: 7,
  branchId: 'branch-vbdl',
  phaiName: 'Phái II-VBĐL',
  chiName: 'Chi HÀ NHA',
  orderInFamily: 1,
  orderTitle: 'Phu Nhân',
  isAlive: false,
  bio: 'Phu nhân cụ Văn Bá Hạnh. Sanh hạ 8 người con: Văn Bá Phước, Văn Bá Nguyên, Văn Bá Trinh, Văn Bá Tường, Văn Bá Bảo, Văn Bá Hiên, Văn Thị Huệ, Văn Thị Kế.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-702'],
});

// II.8.004: Văn Bá Phước (Chi Hà Nha)
members.push({
  id: 'mem-804',
  fullName: 'Văn Bá Phước',
  courtesyName: 'II.8.004',
  gender: 'male',
  generation: 8,
  branchId: 'branch-vbdl',
  phaiName: 'Phái II-VBĐL',
  chiName: 'Chi HÀ NHA',
  orderInFamily: 1,
  orderTitle: 'Trưởng Chi Đời 8 (Chi Hà Nha)',
  isAlive: false,
  bio: 'Con ông Văn Bá Hạnh và bà Huỳnh Thị Thao, cháu nội ông Văn Bá Thể. Có vợ chánh: Nguyễn Thị Ba, vợ thứ: Nguyễn Thị Bính. Sanh hạ 15 người con.',
  fatherId: 'mem-702',
  motherId: 'mem-702-w',
  spouseIds: ['mem-804-w1', 'mem-804-w2'],
});

members.push({
  id: 'mem-804-w1',
  fullName: 'Nguyễn Thị Ba',
  gender: 'female',
  generation: 8,
  branchId: 'branch-vbdl',
  phaiName: 'Phái II-VBĐL',
  orderInFamily: 1,
  orderTitle: 'Chánh Thất',
  isAlive: false,
  bio: 'Vợ chánh cụ Văn Bá Phước.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-804'],
});

members.push({
  id: 'mem-804-w2',
  fullName: 'Nguyễn Thị Bính',
  gender: 'female',
  generation: 8,
  branchId: 'branch-vbdl',
  phaiName: 'Phái II-VBĐL',
  orderInFamily: 2,
  orderTitle: 'Thứ Thất',
  isAlive: false,
  bio: 'Vợ thứ cụ Văn Bá Phước.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-804'],
});

// 15 con đời 9 của Văn Bá Phước:
const phuocChildren = [
  { name: 'Văn Bá Thọ', g: 'male', note: '' },
  { name: 'Văn Bá Lễ', g: 'male', note: '' },
  { name: 'Văn Bá Hoạch', g: 'male', note: '' },
  { name: 'Văn Bá Quý', g: 'male', note: 'Bắt đầu: Phái II-VBĐL-Chi LAM PHỤNG (Ô. Văn Bá Hóa Đ13)' },
  { name: 'Văn Bá Quyến', g: 'male', note: '' },
  { name: 'Văn Thị Quế', g: 'female', note: '' },
  { name: 'Văn Thị Lan', g: 'female', note: '' },
  { name: 'Văn Thị Huấn', g: 'female', note: '' },
  { name: 'Văn Thị Dụ', g: 'female', note: '' },
  { name: 'Văn Thị Nghị', g: 'female', note: '' },
  { name: 'Văn Thị An', g: 'female', note: '' },
  { name: 'Văn Thị Hát', g: 'female', note: '' },
  { name: 'Văn Thị Thới', g: 'female', note: 'Thái' },
  { name: 'Văn Thị Thuyết', g: 'female', note: '' },
  { name: 'Văn Thị Nhỏ', g: 'female', note: '' },
];
phuocChildren.forEach((c, idx) => {
  members.push({
    id: `mem-904-${idx + 1}`,
    fullName: c.name,
    gender: c.g,
    generation: 9,
    branchId: 'branch-vbdl',
    phaiName: 'Phái II-VBĐL',
    chiName: c.note.includes('LAM PHỤNG') ? 'Chi LAM PHỤNG' : 'Chi HÀ NHA',
    orderInFamily: idx + 1,
    isAlive: false,
    bio: `Con cụ Văn Bá Phước. ${c.note}`,
    fatherId: 'mem-804',
    motherId: 'mem-804-w1',
    spouseIds: [],
  });
});

// Các con khác của Văn Bá Hạnh (Đời 8):
members.push(
  {
    id: 'mem-802-02',
    fullName: 'Văn Bá Nguyên',
    gender: 'male',
    generation: 8,
    branchId: 'branch-vbdl',
    phaiName: 'Phái II-VBĐL',
    orderInFamily: 2,
    isAlive: false,
    bio: 'Con trai thứ 2 của cụ Văn Bá Hạnh.',
    fatherId: 'mem-702',
    motherId: 'mem-702-w',
    spouseIds: [],
  },
  {
    id: 'mem-802-03',
    fullName: 'Văn Bá Trinh',
    gender: 'male',
    generation: 8,
    branchId: 'branch-vbdl',
    phaiName: 'Phái II-VBĐL',
    orderInFamily: 3,
    isAlive: false,
    bio: 'Con trai thứ 3 của cụ Văn Bá Hạnh.',
    fatherId: 'mem-702',
    motherId: 'mem-702-w',
    spouseIds: [],
  },
  // II.8.005: Văn Bá Tường
  {
    id: 'mem-805',
    fullName: 'Văn Bá Tường',
    courtesyName: 'II.8.005',
    gender: 'male',
    generation: 8,
    branchId: 'branch-vbdl',
    phaiName: 'Phái II-VBĐL',
    chiName: 'Chi HÀ NHA',
    orderInFamily: 4,
    orderTitle: 'Thứ Chi Đời 8 (Chi Hà Nha)',
    isAlive: false,
    bio: 'Con ông Văn Bá Hạnh, cháu nội ông Văn Bá Thể.',
    fatherId: 'mem-702',
    motherId: 'mem-702-w',
    spouseIds: ['mem-805-w'],
  },
  {
    id: 'mem-802-05',
    fullName: 'Văn Bá Bảo',
    gender: 'male',
    generation: 8,
    branchId: 'branch-vbdl',
    phaiName: 'Phái II-VBĐL',
    orderInFamily: 5,
    isAlive: false,
    bio: 'Con trai thứ 5 của cụ Văn Bá Hạnh.',
    fatherId: 'mem-702',
    motherId: 'mem-702-w',
    spouseIds: [],
  },
  {
    id: 'mem-802-06',
    fullName: 'Văn Bá Hiên',
    gender: 'male',
    generation: 8,
    branchId: 'branch-vbdl',
    phaiName: 'Phái II-VBĐL',
    orderInFamily: 6,
    isAlive: false,
    bio: 'Con trai thứ 6 của cụ Văn Bá Hạnh.',
    fatherId: 'mem-702',
    motherId: 'mem-702-w',
    spouseIds: [],
  },
  {
    id: 'mem-802-07',
    fullName: 'Văn Thị Huệ',
    gender: 'female',
    generation: 8,
    branchId: 'branch-vbdl',
    phaiName: 'Phái II-VBĐL',
    orderInFamily: 7,
    isAlive: false,
    bio: 'Con gái cụ Văn Bá Hạnh.',
    fatherId: 'mem-702',
    motherId: 'mem-702-w',
    spouseIds: [],
  },
  {
    id: 'mem-802-08',
    fullName: 'Văn Thị Kế',
    gender: 'female',
    generation: 8,
    branchId: 'branch-vbdl',
    phaiName: 'Phái II-VBĐL',
    orderInFamily: 8,
    isAlive: false,
    bio: 'Con gái cụ Văn Bá Hạnh.',
    fatherId: 'mem-702',
    motherId: 'mem-702-w',
    spouseIds: [],
  }
);

members.push({
  id: 'mem-805-w',
  fullName: 'Nguyễn Thị Lộc',
  gender: 'female',
  generation: 8,
  branchId: 'branch-vbdl',
  phaiName: 'Phái II-VBĐL',
  orderInFamily: 1,
  orderTitle: 'Phu Nhân',
  isAlive: false,
  bio: 'Vợ cụ Văn Bá Tường.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-805'],
});

// 7 con đời 9 của Văn Bá Tường (II.8.005):
const tuongChildren = [
  { name: 'Văn Bá Hưu', g: 'male' },
  { name: 'Văn Bá Hân', g: 'male' },
  { name: 'Văn Bá Duyên', g: 'male', alias: 'Diên' },
  { name: 'Văn Bá Tráng', g: 'male' },
  { name: 'Văn Thị Khâm', g: 'female' },
  { name: 'Văn Thị Khi', g: 'female' },
  { name: 'Văn Thị Diệu', g: 'female' },
];
tuongChildren.forEach((c, idx) => {
  members.push({
    id: `mem-905-${idx + 1}`,
    fullName: c.name,
    courtesyName: c.alias,
    gender: c.g,
    generation: 9,
    branchId: 'branch-vbdl',
    phaiName: 'Phái II-VBĐL',
    chiName: 'Chi HÀ NHA',
    orderInFamily: idx + 1,
    isAlive: false,
    bio: `Con cụ Văn Bá Tường và bà Nguyễn Thị Lộc.`,
    fatherId: 'mem-805',
    motherId: 'mem-805-w',
    spouseIds: [],
  });
});

// ==========================================
// 3. VĂN BÁ - XUYÊN TÂY (CHI 1)
// II.7.003 - Văn Bá Chánh
// II.7.004 - Văn Bá Trực
// II.7.005 - Văn Bá Cực
// II.7.006 - Văn Bá Viên
// ==========================================
// II.7.003: Văn Bá Chánh
members.push({
  id: 'mem-703',
  fullName: 'Văn Bá Chánh',
  courtesyName: 'II.7.003',
  gender: 'male',
  generation: 7,
  branchId: 'branch-vbxt',
  phaiName: 'Phái II-VBXT',
  chiName: 'Chi 1',
  orderInFamily: 1,
  orderTitle: 'Trưởng Nam Đời 7 (Phái II-VBXT-Chi 1)',
  isAlive: false,
  burialLocation: 'Gò Khoai, Xuyên Tây (cải táng 1976 từ xứ Tân Kiều)',
  bio: 'Con ông Văn Bá Trung, cháu nội ông Văn Bá Đình. Mộ táng tại xứ Tân Kiều, năm 1976 cải táng về nghĩa trang Gia tộc tại Gò Khoai, Xuyên Tây.',
  fatherId: 'mem-603',
  motherId: 'mem-603-w',
  spouseIds: ['mem-703-w'],
});

members.push({
  id: 'mem-703-w',
  fullName: 'Nguyễn Thị An',
  gender: 'female',
  generation: 7,
  branchId: 'branch-vbxt',
  phaiName: 'Phái II-VBXT',
  chiName: 'Chi 1',
  orderInFamily: 1,
  orderTitle: 'Phu Nhân',
  isAlive: false,
  burialLocation: 'Gò Khoai, Xuyên Tây (cải táng 1976 từ Cồn Đô)',
  bio: 'Vợ cụ Văn Bá Chánh. Mộ táng tại Cồn Đô, năm 1976 cải táng về nghĩa trang Gia tộc tại Gò Khoai, Xuyên Tây.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-703'],
});

const chanhChildren = [
  { name: 'Văn Bá Thuyên', g: 'male' },
  { name: 'Văn Bá Thăng', g: 'male' },
  { name: 'Văn Thị Diễn', g: 'female' },
  { name: 'Văn Thị Quyến', g: 'female' },
  { name: 'Văn Thị Đóa', g: 'female' },
  { name: 'Văn Thị Súy', g: 'female' },
];
chanhChildren.forEach((c, idx) => {
  members.push({
    id: `mem-803-${idx + 1}`,
    fullName: c.name,
    gender: c.g,
    generation: 8,
    branchId: 'branch-vbxt',
    phaiName: 'Phái II-VBXT',
    chiName: 'Chi 1',
    orderInFamily: idx + 1,
    isAlive: false,
    bio: `Con cụ Văn Bá Chánh và bà Nguyễn Thị An.`,
    fatherId: 'mem-703',
    motherId: 'mem-703-w',
    spouseIds: [],
  });
});

// II.7.004: Văn Bá Trực
members.push({
  id: 'mem-704',
  fullName: 'Văn Bá Trực',
  courtesyName: 'II.7.004',
  gender: 'male',
  generation: 7,
  branchId: 'branch-vbxt',
  phaiName: 'Phái II-VBXT',
  chiName: 'Chi 1',
  orderInFamily: 2,
  orderTitle: 'Thứ Nam Đời 7 (Phái II-VBXT-Chi 1)',
  isAlive: false,
  burialLocation: 'Gò Khoai, Xuyên Tây (cải táng 1976 từ Cồn Đô)',
  bio: 'Con ông Văn Bá Trung, cháu nội ông Văn Bá Đình. Mộ táng tại Cồn Đô, năm 1976 cải táng về nghĩa trang Gia tộc tại Gò Khoai, Xuyên Tây.',
  fatherId: 'mem-603',
  motherId: 'mem-603-w',
  spouseIds: ['mem-704-w'],
});

members.push({
  id: 'mem-704-w',
  fullName: 'Nguyễn Thị Dịch',
  gender: 'female',
  generation: 7,
  branchId: 'branch-vbxt',
  phaiName: 'Phái II-VBXT',
  chiName: 'Chi 1',
  orderInFamily: 1,
  orderTitle: 'Phu Nhân',
  isAlive: false,
  burialLocation: 'Gò Khoai, Xuyên Tây (cải táng 1976 từ Cồn Đô)',
  bio: 'Vợ cụ Văn Bá Trực. Mộ táng tại Cồn Đô, năm 1976 cải táng về nghĩa trang Gia tộc tại Gò Khoai, Xuyên Tây.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-704'],
});

// Con của Văn Bá Trực gồm:
// 1. Văn Bá Dinh, 2. Văn Bá Môn, 3. Văn Bá Chót
// 4. Văn Bá Bạt (II.8.006 - Nhánh 1 Hà Dục Đông)
// 5. Văn Bá Trích (II.8.007 - Nhánh 2)
// 6. Văn Thị Bót, 7. Văn Thị Bích
members.push(
  {
    id: 'mem-804-01',
    fullName: 'Văn Bá Dinh',
    gender: 'male',
    generation: 8,
    branchId: 'branch-vbxt',
    phaiName: 'Phái II-VBXT',
    chiName: 'Chi 1',
    orderInFamily: 1,
    isAlive: false,
    bio: 'Con trai trưởng cụ Văn Bá Trực và bà Nguyễn Thị Dịch.',
    fatherId: 'mem-704',
    motherId: 'mem-704-w',
    spouseIds: [],
  },
  {
    id: 'mem-804-02',
    fullName: 'Văn Bá Môn',
    gender: 'male',
    generation: 8,
    branchId: 'branch-vbxt',
    phaiName: 'Phái II-VBXT',
    chiName: 'Chi 1',
    orderInFamily: 2,
    isAlive: false,
    bio: 'Con trai thứ 2 cụ Văn Bá Trực.',
    fatherId: 'mem-704',
    motherId: 'mem-704-w',
    spouseIds: [],
  },
  {
    id: 'mem-804-03',
    fullName: 'Văn Bá Chót',
    gender: 'male',
    generation: 8,
    branchId: 'branch-vbxt',
    phaiName: 'Phái II-VBXT',
    chiName: 'Chi 1',
    orderInFamily: 3,
    isAlive: false,
    bio: 'Con trai thứ 3 cụ Văn Bá Trực.',
    fatherId: 'mem-704',
    motherId: 'mem-704-w',
    spouseIds: [],
  },
  // II.8.006: Văn Bá Bạt (Nhánh 1 Hà Dục Đông)
  {
    id: 'mem-806',
    fullName: 'Văn Bá Bạt',
    courtesyName: 'Bạc (II.8.006)',
    gender: 'male',
    generation: 8,
    branchId: 'branch-vbxt',
    phaiName: 'Phái II-VBXT',
    chiName: 'Chi 1',
    nhanhName: 'Nhánh 1 (Hà Dục Đông)',
    orderInFamily: 4,
    orderTitle: 'Khởi đầu Nhánh 1 Hà Dục Đông (II.8.006)',
    isAlive: false,
    burialLocation: 'Hà Lôi',
    bio: 'Con ông Văn Bá Trực, cháu nội ông Văn Bá Trung. Khởi đầu hình thành Phái II-VBXT-Chi 1-Nhánh 1 (Hà Dục Đông), nay ở Thị trấn Ái Nghĩa, huyện Đại Lộc.',
    fatherId: 'mem-704',
    motherId: 'mem-704-w',
    spouseIds: ['mem-806-w'],
  },
  // II.8.007: Văn Bá Trích (Nhánh 2)
  {
    id: 'mem-807',
    fullName: 'Văn Bá Trích',
    courtesyName: 'II.8.007',
    gender: 'male',
    generation: 8,
    branchId: 'branch-vbxt',
    phaiName: 'Phái II-VBXT',
    chiName: 'Chi 1',
    nhanhName: 'Nhánh 2',
    orderInFamily: 5,
    orderTitle: 'Khởi đầu Nhánh 2 (II.8.007)',
    isAlive: false,
    deathDateLunar: '18/03 ÂL',
    burialLocation: 'Gò Khoai, Xuyên Tây (cải táng 1976 từ Cồn Đô)',
    bio: 'Con ông Văn Bá Trực, cháu nội ông Văn Bá Trung. Khởi đầu hình thành Phái II-VBXT-Chi 1-Nhánh 2. Mất ngày 18-3 ÂL.',
    fatherId: 'mem-704',
    motherId: 'mem-704-w',
    spouseIds: ['mem-807-w'],
  },
  {
    id: 'mem-804-06',
    fullName: 'Văn Thị Bót',
    gender: 'female',
    generation: 8,
    branchId: 'branch-vbxt',
    phaiName: 'Phái II-VBXT',
    chiName: 'Chi 1',
    orderInFamily: 6,
    isAlive: false,
    bio: 'Con gái cụ Văn Bá Trực.',
    fatherId: 'mem-704',
    motherId: 'mem-704-w',
    spouseIds: [],
  },
  {
    id: 'mem-804-07',
    fullName: 'Văn Thị Bích',
    gender: 'female',
    generation: 8,
    branchId: 'branch-vbxt',
    phaiName: 'Phái II-VBXT',
    chiName: 'Chi 1',
    orderInFamily: 7,
    isAlive: false,
    bio: 'Con gái cụ Văn Bá Trực.',
    fatherId: 'mem-704',
    motherId: 'mem-704-w',
    spouseIds: [],
  }
);

// Vợ và con của Văn Bá Bạt (II.8.006):
members.push({
  id: 'mem-806-w',
  fullName: 'Văn Phú Thị Thiềm',
  gender: 'female',
  generation: 8,
  branchId: 'branch-vbxt',
  phaiName: 'Phái II-VBXT',
  chiName: 'Chi 1',
  nhanhName: 'Nhánh 1 (Hà Dục Đông)',
  orderInFamily: 1,
  orderTitle: 'Phu Nhân',
  isAlive: false,
  burialLocation: 'Gò Khoai, Xuyên Tây (cải táng 1976 từ Bàu Sen)',
  bio: 'Vợ cụ Văn Bá Bạt. Mộ táng tại Bàu Sen, năm 1976 cải táng về nghĩa trang Gia tộc tại Gò Khoai, Xuyên Tây.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-806'],
});

const batChildren = [
  { name: 'Văn Bá Thâm', g: 'male' },
  { name: 'Văn Bá Hoài', g: 'male' },
  { name: 'Văn Bá Điền', g: 'male' },
  { name: 'Văn Thị Mới', g: 'female' },
];
batChildren.forEach((c, idx) => {
  members.push({
    id: `mem-906-${idx + 1}`,
    fullName: c.name,
    gender: c.g,
    generation: 9,
    branchId: 'branch-vbxt',
    phaiName: 'Phái II-VBXT',
    chiName: 'Chi 1',
    nhanhName: 'Nhánh 1 (Hà Dục Đông)',
    orderInFamily: idx + 1,
    isAlive: false,
    bio: `Con cụ Văn Bá Bạt và bà Văn Phú Thị Thiềm.`,
    fatherId: 'mem-806',
    motherId: 'mem-806-w',
    spouseIds: [],
  });
});

// Vợ và con của Văn Bá Trích (II.8.007):
members.push({
  id: 'mem-807-w',
  fullName: 'Lê Thị Yến',
  gender: 'female',
  generation: 8,
  branchId: 'branch-vbxt',
  phaiName: 'Phái II-VBXT',
  chiName: 'Chi 1',
  nhanhName: 'Nhánh 2',
  orderInFamily: 1,
  orderTitle: 'Phu Nhân',
  isAlive: false,
  burialLocation: 'Gò Khoai, Xuyên Tây (cải táng 1976 từ Cồn Đô)',
  bio: 'Người tộc Lê trong làng. Vợ cụ Văn Bá Trích. Mộ táng Cồn Đô, năm 1976 cải táng về Gò Khoai.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-807'],
});

const trichChildren = [
  { name: 'Văn Bá Mai', g: 'male' },
  { name: 'Văn Bá Nhung', g: 'male' },
  { name: 'Văn Bá Nhân', g: 'male', alias: 'Nhẩn' },
  { name: 'Văn Bá Nhi', g: 'male' },
  { name: 'Văn Thị Ý', g: 'female' },
  { name: 'Văn Thị Trưa', g: 'female' },
  { name: 'Văn Thị Bữa', g: 'female' },
];
trichChildren.forEach((c, idx) => {
  members.push({
    id: `mem-907-${idx + 1}`,
    fullName: c.name,
    courtesyName: c.alias,
    gender: c.g,
    generation: 9,
    branchId: 'branch-vbxt',
    phaiName: 'Phái II-VBXT',
    chiName: 'Chi 1',
    nhanhName: 'Nhánh 2',
    orderInFamily: idx + 1,
    isAlive: false,
    bio: `Con cụ Văn Bá Trích và bà Lê Thị Yến.`,
    fatherId: 'mem-807',
    motherId: 'mem-807-w',
    spouseIds: [],
  });
});

// II.7.005: Văn Bá Cực
members.push({
  id: 'mem-705-cuc',
  fullName: 'Văn Bá Cực',
  courtesyName: 'II.7.005',
  gender: 'male',
  generation: 7,
  branchId: 'branch-vbxt',
  phaiName: 'Phái II-VBXT',
  chiName: 'Chi 1',
  orderInFamily: 3,
  orderTitle: 'Thứ Nam Đời 7 (Phái II-VBXT-Chi 1)',
  isAlive: false,
  burialLocation: 'Gò Khoai, Xuyên Tây (cải táng 1976 từ Bàu Sen)',
  bio: 'Con ông Văn Bá Trung, cháu nội ông Văn Bá Đình. Mộ táng tại Bàu Sen, năm 1976 cải táng về nghĩa trang Gia tộc tại Gò Khoai, Xuyên Tây.',
  fatherId: 'mem-603',
  motherId: 'mem-603-w',
  spouseIds: ['mem-705-w'],
});

members.push({
  id: 'mem-705-w',
  fullName: 'Nguyễn Thị Tư',
  gender: 'female',
  generation: 7,
  branchId: 'branch-vbxt',
  phaiName: 'Phái II-VBXT',
  chiName: 'Chi 1',
  orderInFamily: 1,
  orderTitle: 'Phu Nhân',
  isAlive: false,
  burialLocation: 'Gò Khoai, Xuyên Tây (cải táng 1976 từ Bàu Sen)',
  bio: 'Vợ cụ Văn Bá Cực. Mộ táng tại Bàu Sen, năm 1976 cải táng về nghĩa trang Gia tộc tại Gò Khoai, Xuyên Tây.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-705-cuc'],
});

// II.8.008: Văn Bá Chấn (Phấn, Trừng)
members.push({
  id: 'mem-808',
  fullName: 'Văn Bá Chấn',
  courtesyName: 'Trừng, Phấn (II.8.008)',
  gender: 'male',
  generation: 8,
  branchId: 'branch-vbxt',
  phaiName: 'Phái II-VBXT',
  chiName: 'Chi 1',
  orderInFamily: 1,
  orderTitle: 'Trưởng Chi Đời 8 (Chi 1)',
  isAlive: false,
  burialLocation: 'Gò Khoai, Xuyên Tây (cải táng 1976 từ xứ Bàu Sen)',
  bio: 'Con ông Văn Bá Cực, cháu nội ông Văn Bá Trung. Mộ táng tại xứ Bàu Sen, năm 1976 cải táng về nghĩa trang Gia tộc tại Gò Khoai, Xuyên Tây.',
  fatherId: 'mem-705-cuc',
  motherId: 'mem-705-w',
  spouseIds: ['mem-808-w'],
});

members.push({
  id: 'mem-808-w',
  fullName: 'Nguyễn Thị Tam',
  gender: 'female',
  generation: 8,
  branchId: 'branch-vbxt',
  phaiName: 'Phái II-VBXT',
  chiName: 'Chi 1',
  orderInFamily: 1,
  orderTitle: 'Phu Nhân',
  isAlive: false,
  bio: 'Vợ cụ Văn Bá Chấn.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-808'],
});

const chanChildren = [
  { name: 'Văn Bá Yến', g: 'male', alias: 'Yếu' },
  { name: 'Văn Bá Liệt', g: 'male', alias: 'Liếc' },
  { name: 'Văn Bá Tại', g: 'male' },
  { name: 'Văn Thị Tiến', g: 'female' },
  { name: 'Văn Thị Tính', g: 'female', alias: 'Tỉnh' },
  { name: 'Văn Thị Lanh', g: 'female' },
];
chanChildren.forEach((c, idx) => {
  members.push({
    id: `mem-908-${idx + 1}`,
    fullName: c.name,
    courtesyName: c.alias,
    gender: c.g,
    generation: 9,
    branchId: 'branch-vbxt',
    phaiName: 'Phái II-VBXT',
    chiName: 'Chi 1',
    orderInFamily: idx + 1,
    isAlive: false,
    bio: `Con cụ Văn Bá Chấn và bà Nguyễn Thị Tam.`,
    fatherId: 'mem-808',
    motherId: 'mem-808-w',
    spouseIds: [],
  });
});

// II.8.009: Văn Bá Đệ (Nhánh 3)
members.push({
  id: 'mem-809',
  fullName: 'Văn Bá Đệ',
  courtesyName: 'II.8.009',
  gender: 'male',
  generation: 8,
  branchId: 'branch-vbxt',
  phaiName: 'Phái II-VBXT',
  chiName: 'Chi 1',
  nhanhName: 'Nhánh 3',
  orderInFamily: 2,
  orderTitle: 'Khởi đầu Nhánh 3 (II.8.009)',
  isAlive: false,
  burialLocation: 'Gò Khoai, Xuyên Tây (cải táng 1976 từ xứ Tân Kiều)',
  bio: 'Con ông Văn Bá Cực, cháu nội ông Văn Bá Trung. Bắt đầu hình thành Phái II-VBXT-Chi 1-Nhánh 3.',
  fatherId: 'mem-705-cuc',
  motherId: 'mem-705-w',
  spouseIds: ['mem-809-w'],
});

members.push({
  id: 'mem-809-w',
  fullName: 'Nguyễn Thị Lắm',
  courtesyName: 'Lẫm',
  gender: 'female',
  generation: 8,
  branchId: 'branch-vbxt',
  phaiName: 'Phái II-VBXT',
  chiName: 'Chi 1',
  nhanhName: 'Nhánh 3',
  orderInFamily: 1,
  orderTitle: 'Phu Nhân',
  isAlive: false,
  burialLocation: 'Gò Khoai, Xuyên Tây (cải táng 1976 từ Cồn Khế)',
  bio: 'Người tộc Nguyễn Văn trong làng. Vợ cụ Văn Bá Đệ. Mộ táng tại Cồn Khế, năm 1976 cải táng về Gò Khoai.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-809'],
});

const deChildren = [
  { name: 'Văn Bá Đông', g: 'male' },
  { name: 'Văn Bá Tây', g: 'male' },
  { name: 'Văn Thị Quỳ', g: 'female' },
  { name: 'Văn Thị Trì', g: 'female' },
  { name: 'Văn Thị Dời', g: 'female', alias: 'Di' },
];
deChildren.forEach((c, idx) => {
  members.push({
    id: `mem-909-${idx + 1}`,
    fullName: c.name,
    courtesyName: c.alias,
    gender: c.g,
    generation: 9,
    branchId: 'branch-vbxt',
    phaiName: 'Phái II-VBXT',
    chiName: 'Chi 1',
    nhanhName: 'Nhánh 3',
    orderInFamily: idx + 1,
    isAlive: false,
    bio: `Con cụ Văn Bá Đệ và bà Nguyễn Thị Lắm.`,
    fatherId: 'mem-809',
    motherId: 'mem-809-w',
    spouseIds: [],
  });
});

// II.7.006: Văn Bá Viên (Vô tự)
members.push({
  id: 'mem-706-vien',
  fullName: 'Văn Bá Viên',
  courtesyName: 'II.7.006',
  gender: 'male',
  generation: 7,
  branchId: 'branch-vbxt',
  phaiName: 'Phái II-VBXT',
  chiName: 'Chi 1',
  orderInFamily: 4,
  orderTitle: 'Thứ Nam Đời 7 (Phái II-VBXT-Chi 1)',
  isAlive: false,
  bio: 'Con ông Văn Bá Trung, cháu nội ông Văn Bá Đình. Sanh hạ: Vô tự.',
  fatherId: 'mem-603',
  motherId: 'mem-603-w',
  spouseIds: [],
});

// ==========================================
// 4. VĂN BÁ - XUYÊN TÂY (CHI 2)
// II.7.007 - Văn Bá Hiều
// II.7.008 - Văn Bá Họp
// ==========================================
// II.7.007: Văn Bá Hiều
members.push({
  id: 'mem-707-hieu',
  fullName: 'Văn Bá Hiều',
  courtesyName: 'II.7.007',
  gender: 'male',
  generation: 7,
  branchId: 'branch-vbxt',
  phaiName: 'Phái II-VBXT',
  chiName: 'Chi 2',
  orderInFamily: 2,
  orderTitle: 'Trưởng Phái Đời 7 (Phái II-VBXT-Chi 2)',
  isAlive: false,
  burialLocation: 'Gò Khoai, Xuyên Tây (cải táng 1976 từ Bàu Sen)',
  bio: 'Con ông Văn Bá Đài, cháu nội ông Văn Bá Đình. Mộ táng tại Bàu Sen, năm 1976 cải táng về nghĩa trang Gia tộc tại Gò Khoai, Xuyên Tây.',
  fatherId: 'mem-604',
  motherId: 'mem-604-w',
  spouseIds: ['mem-707-hieu-w'],
});

members.push({
  id: 'mem-707-hieu-w',
  fullName: 'Nguyễn Thị Điện',
  gender: 'female',
  generation: 7,
  branchId: 'branch-vbxt',
  phaiName: 'Phái II-VBXT',
  chiName: 'Chi 2',
  orderInFamily: 1,
  orderTitle: 'Phu Nhân',
  isAlive: false,
  burialLocation: 'Gò Khoai, Xuyên Tây (cải táng 1976 từ Cồn Khế)',
  bio: 'Vợ cụ Văn Bá Hiều. Mộ táng tại Cồn Khế, năm 1976 cải táng về nghĩa trang Gia tộc tại Gò Khoai, Xuyên Tây.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-707-hieu'],
});

// Con của Văn Bá Hiều:
// 1. Văn Bá Thuyên (II.8.010)
// 2. Văn Bá Sự (II.8.011)
// 3. Văn Bá Uyển (II.8.012)
// 4. Văn Bá Ẩm (Bắt đầu Phái II-VBXT-Chi 2-Nhánh 1)
// 5. Văn Bá Dược, 6. Văn Bá Duyệt, 7. Văn Thị Nhựt, 8. Văn Thị Yến
members.push(
  // II.8.010: Văn Bá Thuyên
  {
    id: 'mem-810',
    fullName: 'Văn Bá Thuyên',
    courtesyName: 'II.8.010',
    gender: 'male',
    generation: 8,
    branchId: 'branch-vbxt',
    phaiName: 'Phái II-VBXT',
    chiName: 'Chi 2',
    orderInFamily: 1,
    orderTitle: 'Trưởng Chi Đời 8 (Chi 2)',
    isAlive: false,
    burialLocation: 'Gò Khoai, Xuyên Tây (cải táng 1976 từ Cồn Khế)',
    bio: 'Con ông Văn Bá Hiều, cháu nội ông Văn Bá Đài. Mộ táng tại Cồn Khế, năm 1976 cải táng về nghĩa trang Gia tộc tại Gò Khoai, Xuyên Tây.',
    fatherId: 'mem-707-hieu',
    motherId: 'mem-707-hieu-w',
    spouseIds: ['mem-810-w'],
  },
  // II.8.011: Văn Bá Sự
  {
    id: 'mem-811',
    fullName: 'Văn Bá Sự',
    courtesyName: 'II.8.011',
    gender: 'male',
    generation: 8,
    branchId: 'branch-vbxt',
    phaiName: 'Phái II-VBXT',
    chiName: 'Chi 2',
    orderInFamily: 2,
    orderTitle: 'Thứ Chi Đời 8 (Chi 2)',
    isAlive: false,
    burialLocation: 'Gò Khoai, Xuyên Tây (cải táng 1976 từ Cồn Khế)',
    bio: 'Con ông Văn Bá Hiều, cháu nội ông Văn Bá Đài. Mộ táng tại Cồn Khế, năm 1976 cải táng về nghĩa trang Gia tộc tại Gò Khoai, Xuyên Tây. Vô tự.',
    fatherId: 'mem-707-hieu',
    motherId: 'mem-707-hieu-w',
    spouseIds: [],
  },
  // II.8.012: Văn Bá Uyển
  {
    id: 'mem-812',
    fullName: 'Văn Bá Uyển',
    courtesyName: 'Yễn (II.8.012)',
    gender: 'male',
    generation: 8,
    branchId: 'branch-vbxt',
    phaiName: 'Phái II-VBXT',
    chiName: 'Chi 2',
    orderInFamily: 3,
    orderTitle: 'Thứ Chi Đời 8 (Chi 2)',
    isAlive: false,
    burialLocation: 'Gò Khoai, Xuyên Tây (cải táng 1976 từ xứ Tân Kiều)',
    bio: 'Còn gọi là Yễn. Con ông Văn Bá Hiều, cháu nội ông Văn Bá Đài. Mộ táng tại xứ Tân Kiều, năm 1976 cải táng về nghĩa trang Gia tộc tại Gò Khoai, Xuyên Tây.',
    fatherId: 'mem-707-hieu',
    motherId: 'mem-707-hieu-w',
    spouseIds: ['mem-812-w'],
  },
  {
    id: 'mem-807-04',
    fullName: 'Văn Bá Ẩm',
    gender: 'male',
    generation: 8,
    branchId: 'branch-vbxt',
    phaiName: 'Phái II-VBXT',
    chiName: 'Chi 2',
    nhanhName: 'Nhánh 1',
    orderInFamily: 4,
    orderTitle: 'Bắt đầu Phái II-VBXT-Chi 2-Nhánh 1',
    isAlive: false,
    bio: 'Con cụ Văn Bá Hiều. Bắt đầu hình thành Phái II-VBXT-Chi 2-Nhánh 1.',
    fatherId: 'mem-707-hieu',
    motherId: 'mem-707-hieu-w',
    spouseIds: [],
  },
  {
    id: 'mem-807-05',
    fullName: 'Văn Bá Dược',
    gender: 'male',
    generation: 8,
    branchId: 'branch-vbxt',
    phaiName: 'Phái II-VBXT',
    chiName: 'Chi 2',
    orderInFamily: 5,
    isAlive: false,
    bio: 'Con cụ Văn Bá Hiều.',
    fatherId: 'mem-707-hieu',
    motherId: 'mem-707-hieu-w',
    spouseIds: [],
  },
  {
    id: 'mem-807-06',
    fullName: 'Văn Bá Duyệt',
    gender: 'male',
    generation: 8,
    branchId: 'branch-vbxt',
    phaiName: 'Phái II-VBXT',
    chiName: 'Chi 2',
    orderInFamily: 6,
    isAlive: false,
    bio: 'Con cụ Văn Bá Hiều.',
    fatherId: 'mem-707-hieu',
    motherId: 'mem-707-hieu-w',
    spouseIds: [],
  },
  {
    id: 'mem-807-07',
    fullName: 'Văn Thị Nhựt',
    gender: 'female',
    generation: 8,
    branchId: 'branch-vbxt',
    phaiName: 'Phái II-VBXT',
    chiName: 'Chi 2',
    orderInFamily: 7,
    isAlive: false,
    bio: 'Con gái cụ Văn Bá Hiều.',
    fatherId: 'mem-707-hieu',
    motherId: 'mem-707-hieu-w',
    spouseIds: [],
  },
  {
    id: 'mem-807-08',
    fullName: 'Văn Thị Yến',
    gender: 'female',
    generation: 8,
    branchId: 'branch-vbxt',
    phaiName: 'Phái II-VBXT',
    chiName: 'Chi 2',
    orderInFamily: 8,
    isAlive: false,
    bio: 'Con gái cụ Văn Bá Hiều.',
    fatherId: 'mem-707-hieu',
    motherId: 'mem-707-hieu-w',
    spouseIds: [],
  }
);

// Vợ và con của Văn Bá Thuyên (II.8.010):
members.push({
  id: 'mem-810-w',
  fullName: 'Nguyễn Thị Sính',
  gender: 'female',
  generation: 8,
  branchId: 'branch-vbxt',
  phaiName: 'Phái II-VBXT',
  chiName: 'Chi 2',
  orderInFamily: 1,
  orderTitle: 'Phu Nhân',
  isAlive: false,
  bio: 'Vợ cụ Văn Bá Thuyên.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-810'],
});

const thuyenChildren = [
  { name: 'Văn Bá Hiền', g: 'male' },
  { name: 'Văn Bá Hiệp', g: 'male' },
  { name: 'Văn Bá Ý', g: 'male' },
  { name: 'Văn Thị Huế', g: 'female', alias: 'Huề' },
  { name: 'Văn Thị Quá', g: 'female' },
];
thuyenChildren.forEach((c, idx) => {
  members.push({
    id: `mem-910-${idx + 1}`,
    fullName: c.name,
    courtesyName: c.alias,
    gender: c.g,
    generation: 9,
    branchId: 'branch-vbxt',
    phaiName: 'Phái II-VBXT',
    chiName: 'Chi 2',
    orderInFamily: idx + 1,
    isAlive: false,
    bio: `Con cụ Văn Bá Thuyên và bà Nguyễn Thị Sính.`,
    fatherId: 'mem-810',
    motherId: 'mem-810-w',
    spouseIds: [],
  });
});

// Vợ và con của Văn Bá Uyển (II.8.012):
members.push({
  id: 'mem-812-w',
  fullName: 'Nguyễn Thị Đào',
  gender: 'female',
  generation: 8,
  branchId: 'branch-vbxt',
  phaiName: 'Phái II-VBXT',
  chiName: 'Chi 2',
  orderInFamily: 1,
  orderTitle: 'Phu Nhân',
  isAlive: false,
  burialLocation: 'Gò Khoai, Xuyên Tây (cải táng 1976 từ xứ Tân Kiều)',
  bio: 'Vợ cụ Văn Bá Uyển. Mộ táng tại xứ Tân Kiều, năm 1976 cải táng về nghĩa trang Gia tộc tại Gò Khoai, Xuyên Tây.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-812'],
});

const uyenChildren = [
  { name: 'Văn Bá Múa', g: 'male' },
  { name: 'Văn Bá Miệng', g: 'male' },
  { name: 'Văn Bá Trừng', g: 'male' },
  { name: 'Văn Bá Ưa', g: 'male' },
  { name: 'Văn Thị Thụy', g: 'female' },
  { name: 'Văn Thị Hồi', g: 'female' },
  { name: 'Văn Thị Mật', g: 'female' },
  { name: 'Văn Thị Éo', g: 'female' },
  { name: 'Văn Thị Thuận', g: 'female' },
];
uyenChildren.forEach((c, idx) => {
  members.push({
    id: `mem-912-${idx + 1}`,
    fullName: c.name,
    gender: c.g,
    generation: 9,
    branchId: 'branch-vbxt',
    phaiName: 'Phái II-VBXT',
    chiName: 'Chi 2',
    orderInFamily: idx + 1,
    isAlive: false,
    bio: `Con cụ Văn Bá Uyển và bà Nguyễn Thị Đào.`,
    fatherId: 'mem-812',
    motherId: 'mem-812-w',
    spouseIds: [],
  });
});

// II.7.008: Văn Bá Họp
members.push({
  id: 'mem-708-hop',
  fullName: 'Văn Bá Họp',
  courtesyName: 'II.7.008',
  gender: 'male',
  generation: 7,
  branchId: 'branch-vbxt',
  phaiName: 'Phái II-VBXT',
  chiName: 'Chi 2',
  orderInFamily: 3,
  orderTitle: 'Thứ Nam Đời 7 (Phái II-VBXT-Chi 2)',
  isAlive: false,
  birthPlace: 'Duy Xuyên, Quảng Nam',
  deathDateLunar: '06/08 ÂL',
  burialLocation: 'Gò Khoai, Xuyên Tây (cải táng 1976 từ Bàu Sen)',
  bio: 'Con ông Văn Bá Đài, cháu nội ông Văn Bá Đình. Mất ngày: 06/8 ÂL. Mộ táng tại Bàu Sen, năm 1976 cải táng về nghĩa trang Gia tộc tại Gò Khoai, Xuyên Tây.',
  fatherId: 'mem-604',
  motherId: 'mem-604-w',
  spouseIds: ['mem-708-hop-w'],
});

members.push({
  id: 'mem-708-hop-w',
  fullName: 'Văn Phú Thị Huyến',
  gender: 'female',
  generation: 7,
  branchId: 'branch-vbxt',
  phaiName: 'Phái II-VBXT',
  chiName: 'Chi 2',
  orderInFamily: 1,
  orderTitle: 'Phu Nhân',
  isAlive: false,
  birthPlace: 'Duy Xuyên, Quảng Nam',
  deathDateLunar: '10/11 ÂL',
  burialLocation: 'Gò Khoai, Xuyên Tây (cải táng 1976 từ Bàu Sen)',
  bio: 'Vợ cụ Văn Bá Họp. Mất ngày: 10/11 ÂL. Mộ táng tại Bàu Sen, năm 1976 cải táng về nghĩa trang Gia tộc tại Gò Khoai, Xuyên Tây.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-708-hop'],
});

const hopChildren = [
  { name: 'Văn Bá Đảng', g: 'male', note: '' },
  { name: 'Văn Bá Điểm', g: 'male', note: 'Bắt đầu Phái II-VBXT-Chi 2-Nhánh 2' },
  { name: 'Văn Bá Viên', g: 'male', alias: 'Diên', note: '' },
  { name: 'Văn Bá Cứ', g: 'male', alias: 'Thiệp', note: '' },
  { name: 'Văn Bá Dụng', g: 'male', note: '' },
  { name: 'Văn Thị Thái', g: 'female', note: '' },
];
hopChildren.forEach((c, idx) => {
  members.push({
    id: `mem-808-hop-${idx + 1}`,
    fullName: c.name,
    courtesyName: c.alias,
    gender: c.g,
    generation: 8,
    branchId: 'branch-vbxt',
    phaiName: 'Phái II-VBXT',
    chiName: 'Chi 2',
    nhanhName: c.note.includes('Nhánh 2') ? 'Nhánh 2' : undefined,
    orderInFamily: idx + 1,
    isAlive: false,
    bio: `Con cụ Văn Bá Họp và bà Văn Phú Thị Huyến. ${c.note}`,
    fatherId: 'mem-708-hop',
    motherId: 'mem-708-hop-w',
    spouseIds: [],
  });
});

// ==========================================
// 5. VĂN PHÚ - XUYÊN ĐÔNG (PHÁI III-VPXĐ)
// III.7.009 -> III.7.025
// ==========================================
// III.7.009: Văn Phú Khánh
members.push({
  id: 'mem-709',
  fullName: 'Văn Phú Khánh',
  courtesyName: 'III.7.009',
  gender: 'male',
  generation: 7,
  branchId: 'branch-vpxd',
  phaiName: 'Phái III-VPXĐ',
  chiName: 'Xuyên Đông',
  orderInFamily: 1,
  isAlive: false,
  bio: 'Con ông Văn Phú Thắng, cháu nội ông Văn Phú Xuyên.',
  fatherId: 'mem-605',
  motherId: 'mem-605-w',
  spouseIds: [],
});
['Văn Phú Đắc', 'Văn Phú Lộc', 'Văn Phú Non'].forEach((name, idx) => {
  members.push({
    id: `mem-809-khanh-${idx + 1}`,
    fullName: name,
    gender: 'male',
    generation: 8,
    branchId: 'branch-vpxd',
    phaiName: 'Phái III-VPXĐ',
    orderInFamily: idx + 1,
    isAlive: false,
    bio: 'Con cụ Văn Phú Khánh.',
    fatherId: 'mem-709',
    motherId: null,
    spouseIds: [],
  });
});

// III.7.010: Văn Phú Lục
members.push({
  id: 'mem-710',
  fullName: 'Văn Phú Lục',
  courtesyName: 'III.7.010',
  gender: 'male',
  generation: 7,
  branchId: 'branch-vpxd',
  phaiName: 'Phái III-VPXĐ',
  chiName: 'Xuyên Đông',
  orderInFamily: 2,
  isAlive: false,
  bio: 'Con ông Văn Phú Lương, cháu nội ông Văn Phú Xuyên.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-710-w'],
});
members.push({
  id: 'mem-710-w',
  fullName: 'Hồ Thị Thọ',
  gender: 'female',
  generation: 7,
  branchId: 'branch-vpxd',
  phaiName: 'Phái III-VPXĐ',
  orderInFamily: 1,
  orderTitle: 'Phu Nhân',
  isAlive: false,
  bio: 'Vợ cụ Văn Phú Lục. Sanh hạ 11 người con.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-710'],
});
const lucChildren = [
  { name: 'Văn Phú Tồn', g: 'male' },
  { name: 'Văn Phú Ưu', g: 'male', alias: 'Hạ' },
  { name: 'Văn Phú Nguyên', g: 'male' },
  { name: 'Văn Phú Hựu', g: 'male' },
  { name: 'Văn Phú Hảo', g: 'male' },
  { name: 'Văn Phú Phụ', g: 'male' },
  { name: 'Văn Thị vô danh', g: 'female' },
  { name: 'Văn Thị Trinh', g: 'female' },
  { name: 'Văn Thị Màu', g: 'female' },
  { name: 'Văn Thị Quyến', g: 'female', alias: 'Quyên' },
  { name: 'Văn Thị Diệu', g: 'female', alias: 'Diện' },
];
lucChildren.forEach((c, idx) => {
  members.push({
    id: `mem-810-luc-${idx + 1}`,
    fullName: c.name,
    courtesyName: c.alias,
    gender: c.g,
    generation: 8,
    branchId: 'branch-vpxd',
    phaiName: 'Phái III-VPXĐ',
    orderInFamily: idx + 1,
    isAlive: false,
    bio: 'Con cụ Văn Phú Lục và bà Hồ Thị Thọ.',
    fatherId: 'mem-710',
    motherId: 'mem-710-w',
    spouseIds: [],
  });
});

// III.7.011: Văn Phú Hoan
members.push({
  id: 'mem-711',
  fullName: 'Văn Phú Hoan',
  courtesyName: 'III.7.011',
  gender: 'male',
  generation: 7,
  branchId: 'branch-vpxd',
  phaiName: 'Phái III-VPXĐ',
  chiName: 'Xuyên Đông',
  orderInFamily: 3,
  isAlive: false,
  bio: 'Con ông Văn Phú Hạnh, cháu nội ông Văn Phú Xuyên.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-711-w'],
});
members.push({
  id: 'mem-711-w',
  fullName: 'Nguyễn Thị Giáo',
  gender: 'female',
  generation: 7,
  branchId: 'branch-vpxd',
  phaiName: 'Phái III-VPXĐ',
  orderInFamily: 1,
  orderTitle: 'Phu Nhân',
  isAlive: false,
  bio: 'Vợ cụ Văn Phú Hoan.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-711'],
});
[
  { name: 'Văn Phú Sách', g: 'male' },
  { name: 'Văn Phú Lược', g: 'male' },
  { name: 'Văn Phú Mưu', g: 'male' },
  { name: 'Văn Thị Khoa', g: 'female' },
].forEach((c, idx) => {
  members.push({
    id: `mem-811-hoan-${idx + 1}`,
    fullName: c.name,
    gender: c.g,
    generation: 8,
    branchId: 'branch-vpxd',
    phaiName: 'Phái III-VPXĐ',
    orderInFamily: idx + 1,
    isAlive: false,
    bio: 'Con cụ Văn Phú Hoan và bà Nguyễn Thị Giáo.',
    fatherId: 'mem-711',
    motherId: 'mem-711-w',
    spouseIds: [],
  });
});

// III.7.012: Văn Phú Hượt
members.push({
  id: 'mem-712',
  fullName: 'Văn Phú Hượt',
  courtesyName: 'III.7.012',
  gender: 'male',
  generation: 7,
  branchId: 'branch-vpxd',
  phaiName: 'Phái III-VPXĐ',
  chiName: 'Xuyên Đông',
  orderInFamily: 4,
  isAlive: false,
  bio: 'Con ông Văn Phú Hạnh, cháu nội ông Văn Phú Xuyên.',
  fatherId: null,
  motherId: null,
  spouseIds: [],
});
[
  { name: 'Văn Phú Thanh', g: 'male', alias: 'Thạnh' },
  { name: 'Văn Thị Nhuận', g: 'female' },
].forEach((c, idx) => {
  members.push({
    id: `mem-812-huot-${idx + 1}`,
    fullName: c.name,
    courtesyName: c.alias,
    gender: c.g,
    generation: 8,
    branchId: 'branch-vpxd',
    phaiName: 'Phái III-VPXĐ',
    orderInFamily: idx + 1,
    isAlive: false,
    bio: 'Con cụ Văn Phú Hượt.',
    fatherId: 'mem-712',
    motherId: null,
    spouseIds: [],
  });
});

// III.7.013: Văn Phú Trứ
members.push({
  id: 'mem-713',
  fullName: 'Văn Phú Trứ',
  courtesyName: 'Niên, Trú (III.7.013)',
  gender: 'male',
  generation: 7,
  branchId: 'branch-vpxd',
  phaiName: 'Phái III-VPXĐ',
  chiName: 'Xuyên Đông',
  orderInFamily: 5,
  isAlive: false,
  bio: 'Thường gọi là Niên, Trú. Con ông Văn Phú Huệ, cháu nội ông Văn Phú Xuyên.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-713-w'],
});
members.push({
  id: 'mem-713-w',
  fullName: 'Nguyễn Thị Xử',
  gender: 'female',
  generation: 7,
  branchId: 'branch-vpxd',
  phaiName: 'Phái III-VPXĐ',
  orderInFamily: 1,
  orderTitle: 'Phu Nhân',
  isAlive: false,
  bio: 'Vợ cụ Văn Phú Trứ.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-713'],
});
[
  { name: 'Văn Phú vô danh', g: 'male' },
  { name: 'Văn Phú Sức', g: 'male' },
  { name: 'Văn Phú Đương', g: 'male' },
  { name: 'Văn Phú Quần', g: 'male' },
  { name: 'Văn Thị Bỉ', g: 'female' },
  { name: 'Văn Thị Mạnh', g: 'female' },
].forEach((c, idx) => {
  members.push({
    id: `mem-813-tru-${idx + 1}`,
    fullName: c.name,
    gender: c.g,
    generation: 8,
    branchId: 'branch-vpxd',
    phaiName: 'Phái III-VPXĐ',
    orderInFamily: idx + 1,
    isAlive: false,
    bio: 'Con cụ Văn Phú Trứ và bà Nguyễn Thị Xử.',
    fatherId: 'mem-713',
    motherId: 'mem-713-w',
    spouseIds: [],
  });
});

// III.7.014: Văn Phú Thi (Tứ)
members.push({
  id: 'mem-714',
  fullName: 'Văn Phú Thi',
  courtesyName: 'Tứ (III.7.014)',
  gender: 'male',
  generation: 7,
  branchId: 'branch-vpxd',
  phaiName: 'Phái III-VPXĐ',
  chiName: 'Xuyên Đông',
  orderInFamily: 6,
  isAlive: false,
  bio: 'Thường gọi là Tứ. Con ông Văn Phú Huệ, cháu nội ông Văn Phú Xuyên.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-714-w'],
});
members.push({
  id: 'mem-714-w',
  fullName: 'Huỳnh Thị Sĩ',
  gender: 'female',
  generation: 7,
  branchId: 'branch-vpxd',
  phaiName: 'Phái III-VPXĐ',
  orderInFamily: 1,
  orderTitle: 'Phu Nhân',
  isAlive: false,
  bio: 'Vợ cụ Văn Phú Thi. Sanh hạ 10 người con.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-714'],
});
const thiChildren = [
  { name: 'Văn Phú Thảo', g: 'male', alias: 'Phụ' },
  { name: 'Văn Phú Trường', g: 'male', alias: 'Tường' },
  { name: 'Văn Phú Thiểu', g: 'male' },
  { name: 'Văn Phú Thạch', g: 'male', alias: 'Trạch' },
  { name: 'Văn Thị Sa', g: 'female', alias: 'Tộ' },
  { name: 'Văn Thị Huân', g: 'female' },
  { name: 'Văn Phú Nhuận', g: 'male' },
  { name: 'Văn Phú Nghĩa', g: 'male' },
  { name: 'Văn Thị Ngâm', g: 'female', alias: 'Ngân' },
  { name: 'Văn Thị Linh', g: 'female' },
];
thiChildren.forEach((c, idx) => {
  members.push({
    id: `mem-814-thi-${idx + 1}`,
    fullName: c.name,
    courtesyName: c.alias,
    gender: c.g,
    generation: 8,
    branchId: 'branch-vpxd',
    phaiName: 'Phái III-VPXĐ',
    orderInFamily: idx + 1,
    isAlive: false,
    bio: 'Con cụ Văn Phú Thi và bà Huỳnh Thị Sĩ.',
    fatherId: 'mem-714',
    motherId: 'mem-714-w',
    spouseIds: [],
  });
});

// III.7.015: Văn Phú Chiếu (Mỹ)
members.push({
  id: 'mem-715',
  fullName: 'Văn Phú Chiếu',
  courtesyName: 'Mỹ (III.7.015)',
  gender: 'male',
  generation: 7,
  branchId: 'branch-vpxd',
  phaiName: 'Phái III-VPXĐ',
  chiName: 'Xuyên Đông',
  orderInFamily: 7,
  isAlive: false,
  bio: 'Thường gọi là Mỹ. Con ông Văn Phú Liễu, cháu nội ông Văn Phú Thọ.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-715-w'],
});
members.push({
  id: 'mem-715-w',
  fullName: 'Nguyễn Thị Sử',
  courtesyName: 'Sở',
  gender: 'female',
  generation: 7,
  branchId: 'branch-vpxd',
  phaiName: 'Phái III-VPXĐ',
  orderInFamily: 1,
  orderTitle: 'Phu Nhân',
  isAlive: false,
  bio: 'Vợ cụ Văn Phú Chiếu.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-715'],
});
['Văn Phú Nghị', 'Văn Phú Nghi'].forEach((name, idx) => {
  members.push({
    id: `mem-815-chieu-${idx + 1}`,
    fullName: name,
    gender: 'male',
    generation: 8,
    branchId: 'branch-vpxd',
    phaiName: 'Phái III-VPXĐ',
    orderInFamily: idx + 1,
    isAlive: false,
    bio: 'Con cụ Văn Phú Chiếu và bà Nguyễn Thị Sử.',
    fatherId: 'mem-715',
    motherId: 'mem-715-w',
    spouseIds: [],
  });
});

// III.7.016: Văn Phú Nhơn
members.push({
  id: 'mem-716',
  fullName: 'Văn Phú Nhơn',
  courtesyName: 'III.7.016',
  gender: 'male',
  generation: 7,
  branchId: 'branch-vpxd',
  phaiName: 'Phái III-VPXĐ',
  chiName: 'Xuyên Đông',
  orderInFamily: 8,
  isAlive: false,
  bio: 'Con ông Văn Phú Liễu, cháu nội ông Văn Phú Thọ.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-716-w'],
});
members.push({
  id: 'mem-716-w',
  fullName: 'Nguyễn Thị Đóa',
  gender: 'female',
  generation: 7,
  branchId: 'branch-vpxd',
  phaiName: 'Phái III-VPXĐ',
  orderInFamily: 1,
  orderTitle: 'Phu Nhân',
  isAlive: false,
  bio: 'Vợ cụ Văn Phú Nhơn.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-716'],
});
[
  { name: 'Văn Phú Nghiễm', g: 'male' },
  { name: 'Văn Phú Triết', g: 'male' },
  { name: 'Văn Phú Trị', g: 'male' },
  { name: 'Văn Phú Bảo', g: 'male' },
  { name: 'Văn Thị Lựu', g: 'female', alias: 'Văn Phú Lựu' },
].forEach((c, idx) => {
  members.push({
    id: `mem-816-nhon-${idx + 1}`,
    fullName: c.name,
    courtesyName: c.alias,
    gender: c.g,
    generation: 8,
    branchId: 'branch-vpxd',
    phaiName: 'Phái III-VPXĐ',
    orderInFamily: idx + 1,
    isAlive: false,
    bio: 'Con cụ Văn Phú Nhơn và bà Nguyễn Thị Đóa.',
    fatherId: 'mem-716',
    motherId: 'mem-716-w',
    spouseIds: [],
  });
});

// III.7.017: Văn Phú Yến (Tứ, Trị)
members.push({
  id: 'mem-717',
  fullName: 'Văn Phú Yến',
  courtesyName: 'Tứ, Trị (III.7.017)',
  gender: 'male',
  generation: 7,
  branchId: 'branch-vpxd',
  phaiName: 'Phái III-VPXĐ',
  chiName: 'Xuyên Đông',
  orderInFamily: 9,
  isAlive: false,
  deathDateLunar: '26/11 ÂL',
  bio: 'Thường gọi là Tứ, Trị. Con ông Văn Phú Liễu, cháu nội ông Văn Phú Thọ. Mất ngày: 26/11 ÂL.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-717-w'],
});
members.push({
  id: 'mem-717-w',
  fullName: 'Nguyễn Thị Trụ',
  courtesyName: 'Trú',
  gender: 'female',
  generation: 7,
  branchId: 'branch-vpxd',
  phaiName: 'Phái III-VPXĐ',
  orderInFamily: 1,
  orderTitle: 'Phu Nhân',
  isAlive: false,
  deathDateLunar: '02/11 ÂL',
  bio: 'Vợ cụ Văn Phú Yến. Mất ngày: 02/11 ÂL.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-717'],
});
[
  { name: 'Văn Phú Hy', g: 'male' },
  { name: 'Văn Phú Hưu', g: 'male' },
  { name: 'Văn Phú Hảo', g: 'male' },
  { name: 'Văn Phú Phụ', g: 'male' },
  { name: 'Văn Phú Minh', g: 'male', alias: 'Ninh' },
  { name: 'Văn Phú Thứ', g: 'male' },
  { name: 'Văn Phú Lợi', g: 'male' },
  { name: 'Văn Phú Lãnh', g: 'male', alias: 'Lanh' },
  { name: 'Văn Phú Huệ', g: 'male' },
].forEach((c, idx) => {
  members.push({
    id: `mem-817-yen-${idx + 1}`,
    fullName: c.name,
    courtesyName: c.alias,
    gender: c.g,
    generation: 8,
    branchId: 'branch-vpxd',
    phaiName: 'Phái III-VPXĐ',
    orderInFamily: idx + 1,
    isAlive: false,
    bio: 'Con cụ Văn Phú Yến và bà Nguyễn Thị Trụ.',
    fatherId: 'mem-717',
    motherId: 'mem-717-w',
    spouseIds: [],
  });
});

// III.7.018: Văn Phú Hưng
members.push({
  id: 'mem-718',
  fullName: 'Văn Phú Hưng',
  courtesyName: 'III.7.018',
  gender: 'male',
  generation: 7,
  branchId: 'branch-vpxd',
  phaiName: 'Phái III-VPXĐ',
  chiName: 'Xuyên Đông',
  orderInFamily: 10,
  isAlive: false,
  bio: 'Con ông Văn Phú Trung, cháu nội ông Văn Phú Doãn.',
  fatherId: null,
  motherId: null,
  spouseIds: [],
});
[
  { name: 'Văn Phú Đà', g: 'male' },
  { name: 'Văn Phú Điển', g: 'male' },
  { name: 'Văn Phú Quảng', g: 'male' },
  { name: 'Văn Phú Sanh', g: 'male' },
].forEach((c, idx) => {
  members.push({
    id: `mem-818-hung-${idx + 1}`,
    fullName: c.name,
    gender: c.g,
    generation: 8,
    branchId: 'branch-vpxd',
    phaiName: 'Phái III-VPXĐ',
    orderInFamily: idx + 1,
    isAlive: false,
    bio: 'Con cụ Văn Phú Hưng.',
    fatherId: 'mem-718',
    motherId: null,
    spouseIds: [],
  });
});

// III.7.019: Văn Phú Khoa
members.push({
  id: 'mem-719',
  fullName: 'Văn Phú Khoa',
  courtesyName: 'III.7.019',
  gender: 'male',
  generation: 7,
  branchId: 'branch-vpxd',
  phaiName: 'Phái III-VPXĐ',
  chiName: 'Xuyên Đông',
  orderInFamily: 11,
  isAlive: false,
  bio: 'Con ông Văn Phú Chiếm, cháu nội ông Văn Phú Doãn. Vợ 1: Nguyễn Thị Quyên, Vợ 2: Huỳnh Thị Toại.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-719-w1', 'mem-719-w2'],
});
members.push({
  id: 'mem-719-w1',
  fullName: 'Nguyễn Thị Quyên',
  gender: 'female',
  generation: 7,
  branchId: 'branch-vpxd',
  phaiName: 'Phái III-VPXĐ',
  orderInFamily: 1,
  orderTitle: 'Chánh Thất',
  isAlive: false,
  bio: 'Vợ thứ nhất cụ Văn Phú Khoa.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-719'],
});
members.push({
  id: 'mem-719-w2',
  fullName: 'Huỳnh Thị Toại',
  gender: 'female',
  generation: 7,
  branchId: 'branch-vpxd',
  phaiName: 'Phái III-VPXĐ',
  orderInFamily: 2,
  orderTitle: 'Kế Thất',
  isAlive: false,
  bio: 'Vợ thứ hai cụ Văn Phú Khoa.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-719'],
});
members.push({
  id: 'mem-819-cheo',
  fullName: 'Văn Phú Cheo',
  gender: 'male',
  generation: 8,
  branchId: 'branch-vpxd',
  phaiName: 'Phái III-VPXĐ',
  orderInFamily: 1,
  isAlive: false,
  bio: 'Con cụ Văn Phú Khoa. Theo gia phả chi phái có 8 người con, các gia phả gốc ghi sanh hạ ông Văn Phú Cheo.',
  fatherId: 'mem-719',
  motherId: 'mem-719-w1',
  spouseIds: [],
});

// III.7.020: Văn Phú Kim (Sâm, Pháp)
members.push({
  id: 'mem-720',
  fullName: 'Văn Phú Kim',
  courtesyName: 'Sâm, Pháp (III.7.020)',
  gender: 'male',
  generation: 7,
  branchId: 'branch-vpxd',
  phaiName: 'Phái III-VPXĐ',
  chiName: 'Xuyên Đông',
  orderInFamily: 12,
  isAlive: false,
  deathDateLunar: '06/08 ÂL',
  burialLocation: 'Mỹ An, Gò Nổi, TT. Nam Phước (cải táng 1976 từ xứ Lão Thận, Cồn Hến)',
  bio: 'Thường gọi là Sâm, Pháp. Con ông Văn Phú Hội, cháu nội ông Văn Phú Toàn. Mất ngày 06/8 ÂL. Năm 1976 cải táng về nghĩa trang Gia tộc tại Mỹ An, Gò Nổi, TT. Nam Phước.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-720-w'],
});
members.push({
  id: 'mem-720-w',
  fullName: 'Nguyễn Thị Diện',
  gender: 'female',
  generation: 7,
  branchId: 'branch-vpxd',
  phaiName: 'Phái III-VPXĐ',
  orderInFamily: 1,
  orderTitle: 'Phu Nhân (làng Mỹ Khê)',
  isAlive: false,
  deathDateLunar: '14/08 ÂL',
  burialLocation: 'Mỹ An, Gò Nổi, TT. Nam Phước (cải táng 1976)',
  bio: 'Người làng Mỹ Khê. Mất ngày 14/8 ÂL. Năm 1976 cải táng về nghĩa trang Gia tộc tại Mỹ An, Gò Nổi, TT. Nam Phước.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-720'],
});
[
  { name: 'Văn Phú Kiểm', g: 'male', note: 'Vợ là bà Lê Thị Xuyên' },
  { name: 'Văn Phú Bì', g: 'male', alias: 'Chữ, Liệt', note: 'Bắt đầu: Phái III-VPXĐ-Chi ???-Nhánh ??? (Ô. VP HẠP Đ13)' },
  { name: 'Văn Phú Thừa', g: 'male', note: 'Vợ là bà Lư Thị Từ' },
  { name: 'Văn Thị Kiến', g: 'female', alias: 'Văn Phú Kiếm' },
  { name: 'Văn Thị Hiệp', g: 'female', alias: 'Cận', note: 'Mất: 12/7 ÂL, chồng ở Xuyên Tây' },
  { name: 'Văn Thị Bổn', g: 'female', alias: 'Văn Phú Bốn' },
  { name: 'Văn Thị Vì', g: 'female', alias: 'Dơi', note: 'Có chồng: Nguyễn Kim Trượng cùng làng' },
  { name: 'Văn Thị Hiềm', g: 'female', note: 'Có chồng họ Hồ Tâm cùng làng' },
  { name: 'Văn Thị Thảng', g: 'female' },
].forEach((c, idx) => {
  members.push({
    id: `mem-820-kim-${idx + 1}`,
    fullName: c.name,
    courtesyName: c.alias,
    gender: c.g,
    generation: 8,
    branchId: 'branch-vpxd',
    phaiName: 'Phái III-VPXĐ',
    orderInFamily: idx + 1,
    isAlive: false,
    bio: `Con cụ Văn Phú Kim và bà Nguyễn Thị Diện. ${c.note || ''}`,
    fatherId: 'mem-720',
    motherId: 'mem-720-w',
    spouseIds: [],
  });
});

// III.7.021: Văn Phú Trùm (Lên, Thăng)
members.push({
  id: 'mem-721',
  fullName: 'Văn Phú Trùm',
  courtesyName: 'Lên, Thăng (III.7.021)',
  gender: 'male',
  generation: 7,
  branchId: 'branch-vpxd',
  phaiName: 'Phái III-VPXĐ',
  chiName: 'Xuyên Đông',
  orderInFamily: 13,
  isAlive: false,
  bio: 'Con ông Văn Phú Hội, cháu nội ông Văn Phú Toàn.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-721-w'],
});
members.push({
  id: 'mem-721-w',
  fullName: 'Nguyễn Thị An',
  courtesyName: 'Võ Thị An',
  gender: 'female',
  generation: 7,
  branchId: 'branch-vpxd',
  phaiName: 'Phái III-VPXĐ',
  orderInFamily: 1,
  orderTitle: 'Phu Nhân',
  isAlive: false,
  bio: 'Vợ cụ Văn Phú Trùm. Theo gia phả chi phái tên là Võ Thị An.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-721'],
});
members.push({
  id: 'mem-821-liem',
  fullName: 'Văn Phú Liễm',
  gender: 'male',
  generation: 8,
  branchId: 'branch-vpxd',
  phaiName: 'Phái III-VPXĐ',
  orderInFamily: 1,
  isAlive: false,
  bio: 'Con cụ Văn Phú Trùm và bà Nguyễn Thị An.',
  fatherId: 'mem-721',
  motherId: 'mem-721-w',
  spouseIds: [],
});

// III.7.022: Văn Phú Thượng
members.push({
  id: 'mem-722',
  fullName: 'Văn Phú Thượng',
  courtesyName: 'III.7.022',
  gender: 'male',
  generation: 7,
  branchId: 'branch-vpxd',
  phaiName: 'Phái III-VPXĐ',
  chiName: 'Xuyên Đông',
  orderInFamily: 14,
  isAlive: false,
  bio: 'Con ông Văn Phú Hội, cháu nội ông Văn Phú Toàn.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-722-w'],
});
members.push({
  id: 'mem-722-w',
  fullName: 'Mai Thị Hân',
  gender: 'female',
  generation: 7,
  branchId: 'branch-vpxd',
  phaiName: 'Phái III-VPXĐ',
  orderInFamily: 1,
  orderTitle: 'Phu Nhân',
  isAlive: false,
  bio: 'Vợ cụ Văn Phú Thượng. Sanh hạ 9 người con.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-722'],
});
[
  { name: 'Văn Phú Minh', g: 'male' },
  { name: 'Văn Phú Quá', g: 'male' },
  { name: 'Văn Phú Dương', g: 'male' },
  { name: 'Văn Phú Tựu', g: 'male' },
  { name: 'Văn Phú Nho', g: 'male' },
  { name: 'Văn Thị Lẫn', g: 'female' },
  { name: 'Văn Thị Liên', g: 'female' },
  { name: 'Văn Thị Đặc', g: 'female', alias: 'Được' },
  { name: 'Văn Thị Lạ', g: 'female' },
].forEach((c, idx) => {
  members.push({
    id: `mem-822-thuong-${idx + 1}`,
    fullName: c.name,
    courtesyName: c.alias,
    gender: c.g,
    generation: 8,
    branchId: 'branch-vpxd',
    phaiName: 'Phái III-VPXĐ',
    orderInFamily: idx + 1,
    isAlive: false,
    bio: 'Con cụ Văn Phú Thượng và bà Mai Thị Hân.',
    fatherId: 'mem-722',
    motherId: 'mem-722-w',
    spouseIds: [],
  });
});

// III.7.023: Văn Phú Kim (Văn, Kiêm) - Vào Gia Định
members.push({
  id: 'mem-723',
  fullName: 'Văn Phú Kim',
  courtesyName: 'Văn, Kiêm (III.7.023)',
  gender: 'male',
  generation: 7,
  branchId: 'branch-vpxd',
  phaiName: 'Phái III-VPXĐ',
  chiName: 'Xuyên Đông',
  orderInFamily: 15,
  isAlive: false,
  bio: 'Thường gọi là Văn, Kiêm. Con ông Văn Phú Hiệp, cháu nội ông Văn Phú Toàn. Vào lập nghiệp ở Gia Định thành – Mất tích.',
  fatherId: null,
  motherId: null,
  spouseIds: [],
});
[
  { name: 'Văn Thị Văn', g: 'female' },
  { name: 'Văn Phú Chất', g: 'male' },
  { name: 'Văn Thị Mười', g: 'female' },
  { name: 'Văn Thị Quán', g: 'female' },
  { name: 'Văn Thị Tụy', g: 'female' },
  { name: 'Văn Thị Nhậm', g: 'female' },
].forEach((c, idx) => {
  members.push({
    id: `mem-823-kim-${idx + 1}`,
    fullName: c.name,
    gender: c.g,
    generation: 8,
    branchId: 'branch-vpxd',
    phaiName: 'Phái III-VPXĐ',
    orderInFamily: idx + 1,
    isAlive: false,
    bio: 'Con cụ Văn Phú Kim.',
    fatherId: 'mem-723',
    motherId: null,
    spouseIds: [],
  });
});

// III.7.024: Văn Phú Công
members.push({
  id: 'mem-724',
  fullName: 'Văn Phú Công',
  courtesyName: 'III.7.024',
  gender: 'male',
  generation: 7,
  branchId: 'branch-vpxd',
  phaiName: 'Phái III-VPXĐ',
  chiName: 'Xuyên Đông',
  orderInFamily: 16,
  isAlive: false,
  bio: 'Con ông Văn Phú Hiệp, cháu nội ông Văn Phú Toàn.',
  fatherId: null,
  motherId: null,
  spouseIds: [],
});
[
  { name: 'Văn Thị Bàn', g: 'female' },
  { name: 'Văn Phú Nhậm', g: 'male' },
  { name: 'Văn Thị Thạch', g: 'female' },
  { name: 'Văn Thị Biện', g: 'female' },
].forEach((c, idx) => {
  members.push({
    id: `mem-824-cong-${idx + 1}`,
    fullName: c.name,
    gender: c.g,
    generation: 8,
    branchId: 'branch-vpxd',
    phaiName: 'Phái III-VPXĐ',
    orderInFamily: idx + 1,
    isAlive: false,
    bio: 'Con cụ Văn Phú Công.',
    fatherId: 'mem-724',
    motherId: null,
    spouseIds: [],
  });
});

// III.7.025: Văn Phú Niệm (Học)
members.push({
  id: 'mem-725',
  fullName: 'Văn Phú Niệm',
  courtesyName: 'Học (III.7.025)',
  gender: 'male',
  generation: 7,
  branchId: 'branch-vpxd',
  phaiName: 'Phái III-VPXĐ',
  chiName: 'Xuyên Đông (Ô. VP Cử Đ14)',
  orderInFamily: 17,
  isAlive: false,
  deathDateLunar: '15/11 ÂL',
  burialLocation: 'Quản Thông Viên',
  bio: 'Thường gọi là Học. Con ông Văn Phú Hiệp, cháu nội ông Văn Phú Toàn. Mất ngày 15/11 ÂL. Mộ tại Quản Thông Viên.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-725-w1', 'mem-725-w2'],
});
members.push({
  id: 'mem-725-w1',
  fullName: 'Trần Thị Quyến',
  courtesyName: 'Kính',
  gender: 'female',
  generation: 7,
  branchId: 'branch-vpxd',
  phaiName: 'Phái III-VPXĐ',
  orderInFamily: 1,
  orderTitle: 'Chánh Thất (làng Xuyên Tây)',
  isAlive: false,
  deathDateLunar: '10/01 ÂL',
  burialLocation: 'Cồn Lớn',
  bio: 'Người làng Xuyên Tây. Vợ chánh cụ Văn Phú Niệm. Mất ngày 10/1 ÂL. Mộ tại Cồn Lớn.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-725'],
});
members.push({
  id: 'mem-725-w2',
  fullName: 'Huỳnh Thị Niên',
  gender: 'female',
  generation: 7,
  branchId: 'branch-vpxd',
  phaiName: 'Phái III-VPXĐ',
  orderInFamily: 2,
  orderTitle: 'Kế Thất',
  isAlive: false,
  bio: 'Vợ kế cụ Văn Phú Niệm.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-725'],
});
[
  { name: 'Văn Phú Trữ', g: 'male' },
  { name: 'Văn Phú Ân', g: 'male' },
  { name: 'Văn Phú Nhiệm', g: 'male' },
  { name: 'Văn Thị Học', g: 'female', note: 'Có chồng tộc Văn Công' },
  { name: 'Văn Thị Tuyên', g: 'female' },
  { name: 'Văn Thị Lừa', g: 'female', alias: 'Hoán' },
  { name: 'Văn Thị Hội', g: 'female' },
  { name: 'Văn Thị Huyến', g: 'female' },
].forEach((c, idx) => {
  members.push({
    id: `mem-825-niem-${idx + 1}`,
    fullName: c.name,
    courtesyName: c.alias,
    gender: c.g,
    generation: 8,
    branchId: 'branch-vpxd',
    phaiName: 'Phái III-VPXĐ',
    orderInFamily: idx + 1,
    isAlive: false,
    bio: `Con cụ Văn Phú Niệm. ${c.note || ''}`,
    fatherId: 'mem-725',
    motherId: 'mem-725-w1',
    spouseIds: [],
  });
});

// ==========================================
// 6. VĂN PHÚ - XUYÊN TÂY (PHÁI IV-VPXT)
// IV.7.026 - Văn Phú Đề
// IV.7.027 - Văn Phú Ngân
// ==========================================
// IV.7.026: Văn Phú Đề (Chi 1)
members.push({
  id: 'mem-726',
  fullName: 'Văn Phú Đề',
  courtesyName: 'IV.7.026',
  gender: 'male',
  generation: 7,
  branchId: 'branch-vpxt',
  phaiName: 'Phái IV-VPXT',
  chiName: 'Chi 1',
  orderInFamily: 1,
  orderTitle: 'Trưởng Chi Đời 7 (Phái IV-VPXT-Chi 1)',
  isAlive: false,
  bio: 'Con ông Văn Phú Mính, cháu nội ông Văn Phú Chiếm. Khởi đầu Phái IV-VPXT-Chi 1.',
  fatherId: null,
  motherId: null,
  spouseIds: [],
});
members.push({
  id: 'mem-826-dieu',
  fullName: 'Văn Phú Điều',
  gender: 'male',
  generation: 8,
  branchId: 'branch-vpxt',
  phaiName: 'Phái IV-VPXT',
  chiName: 'Chi 1',
  orderInFamily: 1,
  isAlive: false,
  bio: 'Con cụ Văn Phú Đề.',
  fatherId: 'mem-726',
  motherId: null,
  spouseIds: [],
});

// IV.7.027: Văn Phú Ngân (Chi 2)
members.push({
  id: 'mem-727',
  fullName: 'Văn Phú Ngân',
  courtesyName: 'IV.7.027',
  gender: 'male',
  generation: 7,
  branchId: 'branch-vpxt',
  phaiName: 'Phái IV-VPXT',
  chiName: 'Chi 2',
  orderInFamily: 2,
  orderTitle: 'Trưởng Chi Đời 7 (Phái IV-VPXT-Chi 2)',
  isAlive: false,
  deathDateLunar: '21/02 ÂL',
  bio: 'Con ông Văn Phú Mính, cháu nội ông Văn Phú Chiếm. Mất ngày: 21/2 ÂL.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-727-w'],
});
members.push({
  id: 'mem-727-w',
  fullName: 'Lê Thị Loan',
  courtesyName: 'Lan',
  gender: 'female',
  generation: 7,
  branchId: 'branch-vpxt',
  phaiName: 'Phái IV-VPXT',
  chiName: 'Chi 2',
  orderInFamily: 1,
  orderTitle: 'Phu Nhân',
  isAlive: false,
  deathDateLunar: '06/11 ÂL',
  bio: 'Vợ cụ Văn Phú Ngân. Mất ngày: 06/11 ÂL.',
  fatherId: null,
  motherId: null,
  spouseIds: ['mem-727'],
});
members.push({
  id: 'mem-827-thang',
  fullName: 'Văn Phú Thăng',
  courtesyName: 'Văn Phú Siêu Thăng',
  gender: 'male',
  generation: 8,
  branchId: 'branch-vpxt',
  phaiName: 'Phái IV-VPXT',
  chiName: 'Chi 2',
  orderInFamily: 1,
  isAlive: false,
  bio: 'Còn gọi là Văn Phú Siêu Thăng. Con cụ Văn Phú Ngân và bà Lê Thị Loan.',
  fatherId: 'mem-727',
  motherId: 'mem-727-w',
  spouseIds: [],
});

console.log(`Total new members generated: ${members.length}`);

// Write JSON file to public/clan_data_doi7_8.json
const exportData = {
  version: '2023.07.20',
  description: 'Dữ liệu trích xuất từ Bản thảo GIA PHẢ TỘC VĂN - Đời thứ 7 và Đời thứ 8',
  extractedDate: new Date().toISOString(),
  memberCount: members.length,
  members: members,
};

fs.writeFileSync('public/clan_data_doi7_8.json', JSON.stringify(exportData, null, 2), 'utf8');
console.log('Successfully wrote public/clan_data_doi7_8.json');
